% EXPORT_PAPER_NUMBERS  Write paper/numbers_auto.tex: LaTeX macros for the
% paper's most drift-prone quantitative statements, generated from the SAVED
% results (.mat) so the text can never disagree with the computation.
%
% The paper \input{numbers_auto}s this file; Table 3 (calibrated columns),
% Table 6 (financing regimes), the intro headline shares, and the robustness
% frontier read from these macros. Re-run this script after any driver that
% refreshes calibrated_results / regimes_results / robustness_results, then
% recompile the paper. Macros not yet wired into the text are exported too,
% so future migrations only edit the .tex.
%
% USAGE:  >> cd research_green_deficits; export_paper_numbers

clear; clc;
projdir = fileparts(mfilename('fullpath'));
outf = fullfile(projdir, 'paper', 'numbers_auto.tex');
fid = fopen(outf, 'w');
assert(fid > 0, 'cannot open %s for writing', outf);
fprintf(fid, ['%% numbers_auto.tex -- GENERATED by export_paper_numbers.m ' ...
              'from output/*.mat.\n%% Do not edit by hand; re-run the ' ...
              'exporter after refreshing results.\n']);
mac = @(n, v) fprintf(fid, '\\newcommand{\\%s}{%s}\n', n, v);

% ---- calibrated columns (Table 3, intro headline) ----
L = load(fullfile(projdir, 'output', 'calibrated_results.mat'), 'RCAL');
R = L.RCAL;
suf = {'Low', 'Med', 'High'};
for c = 1:3
    d = R.dec{c};
    mac(['nu'      suf{c}], sprintf('%.3f', d.nu));
    mac(['nuReval' suf{c}], sprintf('%+.3f', d.nu_reval));
    mac(['nuDam'   suf{c}], sprintf('%.3f', d.nu_damage));
    mac(['Pzero'   suf{c}], sprintf('%.3f', d.base.P));
    mac(['Pone'    suf{c}], sprintf('%.3f', d.prog.P));
    mac(['Dzero'   suf{c}], sprintf('%.3f', d.base.D));
    mac(['Done'    suf{c}], sprintf('%.3f', d.prog.D));
    mac(['tauOne'  suf{c}], sprintf('%.3f', d.prog.tau));
    mac(['Wzero'   suf{c}], sprintf('%.2f', d.base.W));
    mac(['Wone'    suf{c}], sprintf('%.2f', d.prog.W));
    mac(['levyAbs' suf{c}], sprintf('%.3f', abs(d.levy)));
end
% short (prose) versions used in the intro/abstract
mac('nuLowShort',  sprintf('%.2f', R.dec{1}.nu));
mac('nuMedShort',  sprintf('%.2f', R.dec{2}.nu));
mac('nuHighShort', sprintf('%.1f', R.dec{3}.nu));
% resource benefit-cost ratio (= nu_damage), 2-dp abstract/prose form
mac('bcrLow',  sprintf('%.2f', R.dec{1}.nu_damage));
mac('bcrMed',  sprintf('%.2f', R.dec{2}.nu_damage));
mac('bcrHigh', sprintf('%.2f', R.dec{3}.nu_damage));
mac('betaStar',    sprintf('%.4f', R.beta_star));
mac('GgCal',       sprintf('%.5f', R.Gg_cal));

% ---- financing regimes (Table 6) ----
L = load(fullfile(projdir, 'output', 'regimes_results.mat'), 'RREG', 'eq0');
G = L.RREG;
rsuf = {'RDef', 'RLev', 'RReb', 'RMix'};
D0med = 0.06;   % medium-column no-abatement damages (Table 3)
for k = 1:4
    % real program g_g1 = (D0 - D1)/nu_dam, self-consistent with the mat
    ggk = (D0med - G(k).D) / G(k).nu_damage;
    mac([rsuf{k} 'P'],      sprintf('%.3f', G(k).P));
    mac([rsuf{k} 'Gg'],     sprintf('%.4f', ggk));
    mac([rsuf{k} 'Done'],   sprintf('%.4f', G(k).D));
    mac([rsuf{k} 'Nu'],     sprintf('%.3f', G(k).nu));
    mac([rsuf{k} 'Rev'],    sprintf('%+.3f', G(k).nu_reval));
    mac([rsuf{k} 'Dam'],    sprintf('%.3f', G(k).nu_damage));
    mac([rsuf{k} 'Bfifty'], sprintf('%+.2f', 100*G(k).lam_b50));
    mac([rsuf{k} 'Tten'],   sprintf('%+.2f', 100*G(k).lam_t10));
end
mac('PzeroRegimes', sprintf('%.4f', L.eq0.P));

% ---- fixed-real financing regimes (referee round 6: pure-incidence panel) ----
% Isolates incidence from the second-order real-scale drift of the fixed-nominal
% table. Guarded: exported only if regimes_fixed_real has been run.
frf = fullfile(projdir, 'output', 'regimes_fixed_real_results.mat');
if exist(frf, 'file') == 2
    F = load(frf, 'RREG');
    for k = 1:min(4, numel(F.RREG))
        mac([rsuf{k} 'RealP'],   sprintf('%.3f',  F.RREG(k).P));
        mac([rsuf{k} 'RealNu'],  sprintf('%.3f',  F.RREG(k).nu));
        mac([rsuf{k} 'RealRev'], sprintf('%+.3f', F.RREG(k).nu_reval));
        mac([rsuf{k} 'RealBfifty'], sprintf('%+.2f', 100*F.RREG(k).lam_b50));
        mac([rsuf{k} 'RealTten'],   sprintf('%+.2f', 100*F.RREG(k).lam_t10));
    end
end

% ---- robustness frontier (Sec 5.7, Table 3 threshold row) ----
L = load(fullfile(projdir, 'output', 'robustness_results.mat'), 'RB');
S = L.RB.surface;
% columns of D0_grid: [0.02 0.06 0.10 0.15 0.20]; sourced = 1,2,5
mac('thetaStarMed',  sprintf('%.2f', S.th_star(2)));
mac('thetaStarHigh', sprintf('%.2f', S.th_star(5)));
nneg = sum(S.NR(:) < 0); ntot = sum(isfinite(S.NR(:)));
mac('nodesNeg', sprintf('%d', nneg));
mac('nodesTot', sprintf('%d', ntot));
% DICE column: nu at theta_g = 2.5 (informative "even at" value)
[~, i25] = min(abs(S.th_grid - 2.5));
mac('nuDiceAtTwoFive', sprintf('%.2f', S.NU(1, i25)));

% ---- tax semi-elasticity map (Sec 5.8; referee round 7) ----
% Guarded: exported only if decompose_tax_elasticity has been run.
tef = fullfile(projdir, 'output', 'tax_elasticity_results.mat');
if exist(tef, 'file') == 2
    T = load(tef);
    mac('epsTau',   sprintf('%+.2f', T.eps_tau));            % baseline d ln S/d tau
    mac('epsLevy',  sprintf('%+.2f', T.eps_levy));           % d ln S/d vartheta (<0)
    % tilt decomposition (memo M2): lump-sum(perRev) = levy(perRev) + tilt
    if isfield(T, 'eps_tilt')
        mac('epsLsPerRev',   sprintf('%+.2f', T.eps_ls_perRev));
        mac('epsLevyPerRev', sprintf('%+.2f', T.eps_levy_perRev));
        mac('epsTilt',       sprintf('%+.2f', T.eps_tilt));
    end
    % covariance form of financing incidence: direct term = Cov(m^b,dy^net),
    % GE tilt, and the implied distribution-shift residual (proposition check)
    if isfield(T, 'cov_perRev') && isfinite(T.cov_perRev)
        mac('covTiltDirect', sprintf('%+.2f', T.cov_perRev));
        mac('covTiltShift',  sprintf('%+.2f', T.cov_shift_resid));
    end
    % share of the tax-induced demand shift from the bottom two baseline quintiles
    if isfield(T,'dS_q') && isfield(T,'dS_tot') && T.dS_tot ~= 0
        mac('epsBotShare', sprintf('%.0f', 100*sum(T.dS_q(1:2))/T.dS_tot));
    end
    % endpoints of each sign-sweep (ordered vals): first / last
    if isfield(T,'sweeps')
        sw = T.sweeps;
        endp = @(v) [v(1) v(end)];
        for s = 1:numel(sw)
            e = endp(sw(s).eps);
            switch s
                case 1, mac('epsAbarLo', sprintf('%+.2f',e(1))); mac('epsAbarHi', sprintf('%+.2f',e(2)));
                case 2, mac('epsRiskLo', sprintf('%+.2f',e(1))); mac('epsRiskHi', sprintf('%+.2f',e(2)));
                case 3, mac('epsSigLo',  sprintf('%+.2f',e(1))); mac('epsSigHi',  sprintf('%+.2f',e(2)));
                case 4, mac('epsBetaLo', sprintf('%+.2f',e(1))); mac('epsBetaHi', sprintf('%+.2f',e(2)));
            end
        end
    end
end

% ---- matched DTPL-vs-NK announcement experiment (run_matched_dtpl_nk) ----
% Guarded: exported only if the matched driver has been run. Percent,
% annualized; DTPL side is the announcement-year deviation from trend.
mkf = fullfile(projdir, 'output', 'matched_dtpl_nk.mat');
if exist(mkf, 'file') == 2
    M = load(mkf, 'pi_impact_ann', 'dtpl_pi1');
    mac('matchedNKimpact', sprintf('%+.2f', 100*M.pi_impact_ann));
    if isfinite(M.dtpl_pi1)
        mac('matchedDTPLimpact', sprintf('%+.2f', 100*M.dtpl_pi1));
    end
end

% ---- decile-resolution welfare incidence (welfare_incidence_deciles) ----
% Guarded: exported only if the decile driver has been run. Medium column
% is index 2 (as for thetaStarMed); regime order matches rsuf (lump-sum,
% levy, levy+rebate, mixed).
wdf = fullfile(projdir, 'output', 'welfare_deciles_results.mat');
if exist(wdf, 'file') == 2
    Wd = load(wdf, 'WD');
    if numel(Wd.WD.cols) >= 2 && ~isempty(Wd.WD.cols{2}) && Wd.WD.cols{2}.ok
        wm = Wd.WD.cols{2};
        mac('WDecBotMed',     sprintf('%+.2f', 100*wm.lambda_dec(1)));
        mac('WDecTopMed',     sprintf('%+.2f', 100*wm.lambda_dec(10)));
        mac('WTopFiveMed',    sprintf('%+.2f', 100*wm.lambda_top5));
        mac('WTopOneMed',     sprintf('%+.2f', 100*wm.lambda_top1));
        mac('WShareTopOneMed', sprintf('%.0f', 100*wm.wshare_top1));
    end
    for k = 1:min(4, numel(Wd.WD.regimes))
        if ~isempty(Wd.WD.regimes{k}) && Wd.WD.regimes{k}.ok
            wr = Wd.WD.regimes{k};
            mac([rsuf{k} 'DecBot'], sprintf('%+.2f', 100*wr.lambda_dec(1)));
            mac([rsuf{k} 'DecTop'], sprintf('%+.2f', 100*wr.lambda_dec(10)));
            mac([rsuf{k} 'TopOne'], sprintf('%+.2f', 100*wr.lambda_top1));
        end
    end
end

% ---- two-asset Step 0 (main_twoasset_step0) ----
% Guarded: exported only after the two-asset driver has run. Nothing in the
% paper asserts these until the run; the appendix scaffold reads them with
% \pendingnum fallbacks.
taf = fullfile(projdir, 'output', 'twoasset_step0.mat');
if exist(taf, 'file') == 2
    TA = load(taf);
    if isfield(TA,'eqb') && isstruct(TA.eqb) && TA.eqb.ok
        mac('TwoAOmega',  sprintf('%.2f', TA.omega));
        mac('TwoASpread', sprintf('%.3f', (TA.eqb.q + TA.d_div)/TA.eqb.q - (1 + TA.r_b)));
        if isfield(TA,'EX') && numel(TA.EX) >= 2
            mac('TwoADlnPLS',   sprintf('%+.3f', TA.EX(1).dlnP));
            mac('TwoADlnPLevy', sprintf('%+.3f', TA.EX(2).dlnP));
            % absorption ratio vs the one-asset lump-sum regime, if available
            rgf = fullfile(projdir, 'output', 'regimes_results.mat');
            if exist(rgf, 'file') == 2
                R1a = load(rgf, 'RREG', 'eq0');
                d1 = log(R1a.RREG(1).P / R1a.eq0.P);
                if isfinite(d1) && d1 ~= 0
                    mac('TwoARatioLS', sprintf('%.2f', TA.EX(1).dlnP / d1));
                end
            end
        end
        if isfield(TA,'ZS') && numel(TA.ZS) >= 2
            zok = TA.ZS([TA.ZS.ok]);
            if numel(zok) >= 2
                mac('TwoAZetaLoP', sprintf('%+.3f', zok(1).dlnP));
                mac('TwoAZetaHiP', sprintf('%+.3f', zok(end).dlnP));
            end
        end
        if isfield(TA,'eLS') && isfinite(TA.eLS)
            mac('TwoAEpsLs',   sprintf('%+.2f', TA.eLS));
            mac('TwoAEpsLevy', sprintf('%+.2f', TA.eLV));
            mac('TwoAEpsTilt', sprintf('%+.2f', TA.eTL));
        end
    end
end

% ---- two-asset variant (b): infrequent adjustment (main_twoasset_kv) ----
tkf = fullfile(projdir, 'output', 'twoasset_kv.mat');
if exist(tkf, 'file') == 2
    TK = load(tkf);
    if isfield(TK,'eqb') && isstruct(TK.eqb) && TK.eqb.ok
        mac('TwoBOmega', sprintf('%.2f', TK.omega));
        if isfield(TK,'H'), mac('TwoBWhtm', sprintf('%.0f', 100*TK.H.whtm)); end
        if isfield(TK,'EXK') && numel(TK.EXK) >= 2
            mac('TwoBDlnPLS',   sprintf('%+.3f', TK.EXK(1).dlnP));
            mac('TwoBDlnPLevy', sprintf('%+.3f', TK.EXK(2).dlnP));
        end
        if isfield(TK,'eLS') && isfinite(TK.eLS)
            mac('TwoBEpsLs',   sprintf('%+.2f', TK.eLS));
            mac('TwoBEpsTilt', sprintf('%+.2f', TK.eTL));
        end
    end
end

% ---- wealth-concentration fit (wealth_concentration_fit) ----
% Guarded: exported only if the superstar-fit driver has been run.
wff = fullfile(projdir, 'output', 'wealth_fit_results.mat');
if exist(wff, 'file') == 2
    Wf = load(wff, 'best', 'dec', 'wd');
    if isfield(Wf, 'best') && isfield(Wf, 'dec')     % skip the NO-FIT case
    mac('SupTopOneShare', sprintf('%.0f', 100*Wf.best.top1));
    mac('SupNuReval',     sprintf('%+.3f', Wf.dec.nu_reval));
    if isfield(Wf, 'wd') && Wf.wd.ok
        mac('SupDecBot', sprintf('%+.2f', 100*Wf.wd.lambda_dec(1)));
        mac('SupDecTop', sprintf('%+.2f', 100*Wf.wd.lambda_dec(10)));
        mac('SupTopOne', sprintf('%+.2f', 100*Wf.wd.lambda_top1));
    end
    end                                              % NO-FIT skip
end

fclose(fid);
fprintf('[export_paper_numbers] wrote %s\n', outf);
