% MAIN_SIGN_MAP  Sign map of the stationary tax-demand semi-elasticity over
% the swept parameter box, with the calibrated point marked and the empirical
% ranges left as documented NaN slots.  (Referee MC2, implementation item iii;
% the same ask appears internally as item X8 of REFEREE_REPORT_INTERNAL_R9.md,
% line 279: "Sign map over (lambda, iota_H, concentration) with the calibrated
% point and external ranges marked".)
%
% PROVENANCE OF THE REFEREE TEXT.  There is no R13 report file in this
% repository -- a repository search for "r13" returns only the two planning documents written alongside this file (CLAIM_STATUS_R13.md, PAPER_ARCHITECTURE_R13.md), neither of which is the referee report itself
% 'A label such as "knife-edge" is not a substitute for measuring the size of
% the sign region' does not appear anywhere in the tree.  It is therefore
% recorded here as transcribed from the task brief, NOT as a quotation this
% driver verified against a source in the repository.  The nearest text that
% IS in the repository is REFEREE_REPORT_INTERNAL_R9.md section 3(b),
% "A knife-edge should be measured, not just labelled", which makes the same
% demand; that is the internal item this driver discharges.
%
% WHY THIS EXISTS.  The paper's green-disinflation result turns on the SIGN of
%   eps_tau = d ln S / d tau,
% the stationary semi-elasticity of aggregate demand for nominal government
% liabilities with respect to the lump-sum tax instrument.  The exact
% decomposition of that response (audit_tax_incidence.m, BLOCK B) splits it
% into a direct policy-flow term evaluated at the FIXED baseline distribution
% and a term generated by movement of the ENDOGENOUS stationary wealth
% distribution.  In the certified one-asset benchmark the distributional term
% carries the great majority of the response, and the MARGINAL direct
% covariance term carries the OPPOSITE sign -- the reading already recorded in
% the header of src_project/kv_wealth_mobility.m.  The paper's empirical
% discipline (constrained shares, MPCs) speaks to the small direct term.  It
% does not speak to the dominant distributional one.
%
% The referee's demand follows: if the sign is asserted, the SIZE of the region
% in which it survives must be measured, not labelled.  This driver measures it.
%
% WHAT IS COMPUTED, PER NODE
%   (1) eps_ls   = d ln S / d tau, forward difference in the lump-sum tax --
%       the SIGN-MAP HEADLINE.  Same object, same protocol and same step as
%       the `semielast` used by decompose_tax_elasticity.m.
%   (2) the EXACT policy/distribution split of that same lump-sum step, by the
%       BLOCK B identity of audit_tax_incidence.m:
%           dS = int (b1' - b0') dOmega0  +  int b1' (dOmega1 - dOmega0)
%       reported per unit of tax and normalised by S0, plus the reconstruction
%       residual (which is a numerical-quality flag, not a result).
%   (3) the mean-zero REGRESSIVE TILT experiment and its own exact split, plus
%       the first-order direct COVARIANCE term Cov(m^b, dy^net)/(S0*rev).
%       The covariance object only exists for a mean-zero perturbation: for a
%       UNIFORM lump-sum tax dy^net is constant across households, so its
%       covariance with the marginal propensity to accumulate is identically
%       zero.  That is why the referee's "-0.07 marginal direct covariance"
%       is a TILT object and is reported here as one.  Do not read the tilt
%       column as the lump-sum column; they are different experiments.
%   (4) a finite-difference stability flag (eps at dtau vs dtau/2) and the
%       household / distribution solver convergence flags.
%   (5) model-side wealth-mobility summaries from the SHARED function
%       src_project/kv_wealth_mobility.m -- the one-step (annual) bin chain,
%       its Shorrocks index, its extreme-bin retentions and its half-life.
%
% WHAT IS REUSED, AND WHY NOTHING IS RE-DERIVED
%   S_green (src_project/S_green.m) is the single definition of stationary
%   aggregate demand; every elasticity here is finite differences of it.  The
%   exact split is the BLOCK B identity of audit_tax_incidence.m applied to the
%   same S_green outputs.  Mobility comes from kv_wealth_mobility, which is
%   already a shared function.  The elasticity formula, the tilt construction,
%   the covariance construction and the calibrated-point protocol (beta_star
%   from output/calibrated_results.mat, D0 = 0.06, r from i_ss and mu,
%   tau0 = r*Bnom/P0 with P0 = Bnom/1.10) are taken from
%   decompose_tax_elasticity.m and audit_tax_incidence.m rather than restated.
%   `semielast` and the BLOCK B lines live inside SCRIPTS, so MATLAB cannot
%   call them from here; the anti-drift device is instead a PARITY GATE at the
%   calibrated node against the numbers those drivers have already written to
%   output/tax_elasticity_results.mat and output/audit_tax_incidence.mat.  The
%   gate prints the gap and flags it; it is informational when the stored run
%   used a different grid, and it is the thing to look at first if this map
%   ever disagrees with the certified drivers.
%
% AXES.  The referee names four dimensions.  Two of them do not exist in the
% certified one-asset economy and are DECLARED BUT NOT POPULATED here:
%   * lambda_adj (adjustment frequency) is a two-asset parameter.
%   * iota_H (direct ownership share) is a two-asset parameter: it enters the
%     two-asset bond-market clearing condition, and the one-asset economy has
%     no fund for it to be a share of.
% The two-asset economy is UNCERTIFIED (see NUMERICAL_ACCEPTANCE_TWO_ASSET_R10
% and TWO_ASSET_FAILURE_FALLBACK_MEMO), so this driver does not run it and
% presents no two-asset number.  Those axes appear in the axis table with
% status UNPOPULATED and the reason stated, so the map is not read as covering
% ground it does not cover.
% The dimensions that ARE populated, all in the certified one-asset economy:
%   * rho     -- persistence of log income: the wealth-mobility primitive.
%   * sig_eps -- income-risk scale: the buffer-stock / liquid-wealth
%                persistence primitive.
%   * third axis, mode-dependent (see MODES below).
%
% TWO MODES, BECAUSE A FIXED-BETA SWEEP CONFOUNDS.  audit_tax_incidence.m
% BLOCK D records the lesson explicitly: with beta held fixed, moving a
% primitive also moves the equilibrium debt target, so the sweep confounds the
% primitive with leverage, and a sign flip may be attributed to the primitive
% only if it also appears in the recalibrated row.  So:
%   'fixed-beta' : beta held at the calibrated beta_star; third axis is a
%                  multiplier on beta (patience itself as a free axis).
%                  The equilibrium debt level S0 MOVES across nodes; the
%                  fraction from this mode alone is CONFOUNDED and is labelled
%                  as such in the summary.
%   'recal-beta' : beta recalibrated at every node by calibrate_beta to hold
%                  the debt/income target; third axis is that target b_target.
%                  This is the un-confounded row and is the one to quote.
% The pooled ("both modes agree") fraction is also reported.
%
% THE DELIVERABLE.  The fraction of the region in which eps_ls > 0.  Two
% fractions are printed and they are NOT interchangeable:
%   (A) SWEPT-BOX fraction -- over every converged node of the grid actually
%       run.  This is a property of the box the author chose, so it is a lower
%       bound on nothing and an estimate of nothing; it is reported because it
%       is what the run measured.
%   (B) ADMISSIBLE-REGION fraction -- over the nodes whose model-side mobility
%       lies inside the externally measured range.  This is the number the
%       referee asked for.  It is PENDING: the empirical ranges below are NaN
%       slots with their sources named, exactly as main_validation_mobility.m
%       leaves its data column, and nothing is entered from memory.  Fill EMP
%       below and re-run; the mask activates automatically and (B) prints.
% Until EMP is filled, the paper may report (A) with its label, and may NOT
% describe it as the size of the admissible sign region.
%
% USAGE   >> clear; main_sign_map
%         >> clear; FAST = true; main_sign_map          % coarse grid, 1 mode
%         >> clear; NA = 250; main_sign_map             % grid override
%         >> clear; RECAL = false; main_sign_map        % skip recalibration
% OUTPUT  output/tables/sign_map.txt, output/sign_map.mat
%         (and PFig_sign_map.* if MAKEFIG and a figure device are available)
%
% RUNTIME.  Five S_green solves per node, plus one calibrate_beta per node in
% recal-beta mode.  The full run is an hours-scale driver at na = 500, in line
% with audit_tax_incidence.  Use FAST for a shape check, never for a number.
%
% STATUS: verification/robustness driver.  No number here is asserted in the
% paper until this has run at the published grid and the parity gate passes.

clearvars -except FAST NA RECAL MAKEFIG; close all; clc;
rng(20260805, 'twister'); t0 = tic;

projdir = fileparts(mfilename('fullpath'));
if isempty(projdir), projdir = pwd; end
cd(projdir);
rootdir = fileparts(projdir);
addpath(genpath(fullfile(rootdir, 'src')));
addpath(genpath(fullfile(projdir, 'src_project')));

if ~exist('FAST','var')    || isempty(FAST),    FAST = false;   end
if ~exist('MAKEFIG','var') || isempty(MAKEFIG), MAKEFIG = true; end

% =====================================================================
% Baseline parameters and the calibrated point.  Protocol copied from
% decompose_tax_elasticity.m / audit_tax_incidence.m so the calibrated node of
% this map IS their benchmark and the parity gate below is meaningful.
% =====================================================================
pg0 = setup_params_green();
if exist('NA','var') && ~isempty(NA)
    pg0.na = NA;
elseif FAST
    pg0.na = pg0.fast.na;
end
pg0 = sm_rebuild_grid(pg0);
pg0.vartheta = 0;                 % explicit: the levy is off at the base

calfile = fullfile(projdir, 'output', 'calibrated_results.mat');
beta_cal_source = 'setup_params_green benchmark (calibrated_results.mat absent)';
if exist(calfile, 'file') == 2
    L = load(calfile);
    if isfield(L, 'RCAL') && isfield(L.RCAL, 'beta_star')
        pg0.beta = L.RCAL.beta_star;
        beta_cal_source = 'output/calibrated_results.mat (RCAL.beta_star)';
    end
end
pg0.climate_version = 1;
pg0.D0 = 0.06;
D0     = pg0.D0;
r_cal  = (1 + pg0.i_ss)/(1 + pg0.mu) - 1;
P0     = pg0.Bnom / 1.10;
tau0   = r_cal * pg0.Bnom / P0;

% Perturbation sizes.  dtau matches decompose_tax_elasticity's sweep step; dv
% and hh match audit_tax_incidence BLOCK B.  Changing any of them changes the
% object, not just its precision -- record them in the output.
dtau = 0.01;
dv   = 0.01;
hh   = 1e-3;
rev  = dv * (1 - D0);
btarget_cal = 1.10;

if ~isfolder(pg0.tabdir), mkdir(pg0.tabdir); end
if ~isfolder(fullfile(projdir, 'output')), mkdir(fullfile(projdir, 'output')); end

% =====================================================================
% EMPIRICAL RANGES -- NaN SLOTS.  Transcribe by hand from the cited sources,
% then re-run.  These are the SAME sources main_validation_mobility.m names for
% its data column, and the same rule applies: a wrong decimal in a validation
% table is worse than an empty one, so nothing is entered from memory and
% nothing is inferred from a remembered figure.
%
% HORIZON MISMATCH, STATED UP FRONT.  The published moments below are at
% two- and five-year horizons.  The mobility summary this driver reports per
% node is the ONE-STEP (annual) bin chain returned by kv_wealth_mobility.  A
% two-year model moment is NOT the one-step bin matrix squared: the bin chain
% is not Markov, because bin membership does not summarise the (a,e) state.
% main_validation_mobility.m builds the horizon-matched model moments properly,
% from the full (a,e) transition, at the calibrated point only.  Extending that
% construction to every node is the remaining work before the mobility mask can
% bind.  Until then MASK_ACTIVE stays false even if numbers are pasted in
% below, unless MASK_HORIZON_OK is also set true by whoever has checked that
% the model statistic and the data statistic are at the same horizon.
% =====================================================================
EMP = struct('name', {}, 'lo', {}, 'hi', {}, 'horizon_yrs', {}, 'src', {});
EMP(end+1) = struct('name', 'q1_stay', 'lo', NaN, 'hi', NaN, 'horizon_yrs', 2, ...
    'src', ['[SCF] Board of Governors, SCF 2007-2009 panel: two-year ' ...
            'net-worth quintile transitions, P(bottom -> bottom).']);
EMP(end+1) = struct('name', 'q5_stay', 'lo', NaN, 'hi', NaN, 'horizon_yrs', 2, ...
    'src', ['[SCF] Board of Governors, SCF 2007-2009 panel: two-year ' ...
            'net-worth quintile transitions, P(top -> top).']);
EMP(end+1) = struct('name', 'shorrocks', 'lo', NaN, 'hi', NaN, 'horizon_yrs', 5, ...
    'src', ['[HLS] Hurst, Luoh & Stafford, "The Wealth Dynamics of American ' ...
            'Families, 1984-94", BPEA 1998(1): PSID wealth-quintile ' ...
            'transition matrices, 1984->1989 and 1989->1994; Shorrocks ' ...
            'trace index (5 - trace)/4 computed from the matrix.']);
EMP(end+1) = struct('name', 'htm_stay', 'lo', NaN, 'hi', NaN, 'horizon_yrs', 2, ...
    'src', ['[KVW] Kaplan, Violante & Weidner, "The Wealthy Hand-to-Mouth", ' ...
            'BPEA 2014(1): persistence of hand-to-mouth status over two ' ...
            'years, POOR-HtM figure (the analogue of the model''s ' ...
            'near-the-limit set).']);
EMP(end+1) = struct('name', 'debt_to_income', 'lo', NaN, 'hi', NaN, 'horizon_yrs', NaN, ...
    'src', ['[DEBT] General-government debt / GDP for the calibration ' ...
            'geography, from the OECD series the calibration appendix ' ...
            'cites.  calibrate_beta.m''s header states the target this ' ...
            'project uses; the admissible RANGE must still be transcribed ' ...
            'from the series, not from that comment.']);
EMP(end+1) = struct('name', 'rho_income', 'lo', NaN, 'hi', NaN, 'horizon_yrs', NaN, ...
    'src', ['[EARN] Annual persistence of log labour income, from the ' ...
            'earnings-process estimate the calibration appendix cites.  ' ...
            'make_income_process.m records rho = 0.90 as the replicator''s ' ...
            'benchmark choice, i.e. NOT itself an external estimate.']);
MASK_HORIZON_OK = false;   % set true only after the horizon check above is done

% MATCHING CAVEAT, carried over verbatim in substance from
% main_validation_mobility.m: the model's wealth is a single liquid asset with
% a borrowing limit, so it maps to NET WORTH EXCLUDING illiquid housing and
% pensions more closely than to total net worth.  Prefer a financial-wealth
% definition where the source offers one, and record which was used.

% =====================================================================
% AXES.  Calibrated values are forced into every populated axis so the
% calibrated node always exists in the map and can be marked.
% =====================================================================
rho_cal = pg0.rho;
sig_cal = pg0.sig_eps0;

if FAST
    rho_ax  = [0.85 0.90 0.95];
    sig_ax  = [0.16 0.20 0.26];
    bmult_ax   = 1.00;
    btarget_ax = btarget_cal;
else
    rho_ax  = [0.80 0.85 0.90 0.94 0.97];
    sig_ax  = [0.14 0.20 0.26];
    bmult_ax   = [0.97 1.00 1.03];
    btarget_ax = [0.90 1.10 1.30];
end
rho_ax     = unique([rho_ax(:); rho_cal]).';
sig_ax     = unique([sig_ax(:); sig_cal]).';
bmult_ax   = unique([bmult_ax(:); 1.00]).';
btarget_ax = unique([btarget_ax(:); btarget_cal]).';

if ~exist('RECAL','var') || isempty(RECAL), RECAL = ~FAST; end
if RECAL
    MODES = {'fixed-beta', 'recal-beta'};
else
    MODES = {'fixed-beta'};
end

% =====================================================================
% PLAN the nodes serially, then evaluate them independently.
% =====================================================================
PLAN = {};
for m = 1:numel(MODES)
    if strcmp(MODES{m}, 'fixed-beta')
        third_ax = bmult_ax;
    else
        third_ax = btarget_ax;
    end
    for ir = 1:numel(rho_ax)
        for is = 1:numel(sig_ax)
            for it = 1:numel(third_ax)
                nd = struct();
                nd.mode    = MODES{m};
                nd.rho     = rho_ax(ir);
                nd.sig     = sig_ax(is);
                if strcmp(MODES{m}, 'fixed-beta')
                    nd.bmult   = third_ax(it);
                    nd.btarget = NaN;
                    nd.is_cal  = (nd.rho == rho_cal) && (nd.sig == sig_cal) ...
                                 && (nd.bmult == 1.00);
                else
                    nd.bmult   = NaN;
                    nd.btarget = third_ax(it);
                    nd.is_cal  = (nd.rho == rho_cal) && (nd.sig == sig_cal) ...
                                 && (nd.btarget == btarget_cal);
                end
                PLAN{end+1} = nd; %#ok<SAGROW>
            end
        end
    end
end
nnode = numel(PLAN);

fprintf('==============================================================\n');
fprintf(' SIGN MAP of the stationary tax-demand semi-elasticity\n');
fprintf('==============================================================\n');
fprintf('na=%d ne=%d  FAST=%d  modes: %s\n', pg0.na, pg0.ne, FAST, strjoin(MODES, ', '));
fprintf('nodes=%d  (5 S_green solves each%s)\n', nnode, ...
        sm_tern(RECAL, ', plus one calibrate_beta per recal-beta node', ''));
fprintf('calibrated point: rho=%.3f sig_eps=%.3f beta=%.4f  [%s]\n', ...
        rho_cal, sig_cal, pg0.beta, beta_cal_source);

% =====================================================================
% EVALUATE.  parfor over independent nodes; the pattern (cell of rows, then
% one concatenation) follows audit_tax_incidence BLOCK D.
% =====================================================================
ROWS = cell(nnode, 1);
parfor k = 1:nnode
    ROWS{k} = sm_eval_node(PLAN{k}, pg0, r_cal, tau0, D0, dtau, dv, hh, rev);
end
N = [ROWS{:}];

% =====================================================================
% PARITY GATE at the calibrated node, against the certified drivers.
% =====================================================================
PAR = sm_parity_gate(projdir, N, pg0.na);

% =====================================================================
% FRACTIONS.
% =====================================================================
use   = [N.conv] & isfinite([N.eps_ls]);
FRAC  = struct();
FRAC.n_total = nnode;
FRAC.n_used  = sum(use);
FRAC.n_fail  = nnode - sum(use);
FRAC.swept_box_pos = NaN;
if FRAC.n_used > 0
    FRAC.swept_box_pos = sum([N(use).eps_ls] > 0) / FRAC.n_used;
end
FRAC.by_mode = struct('mode', {}, 'n_used', {}, 'frac_pos', {}, ...
                      'frac_pos_tilt', {}, 'confounded', {});
for m = 1:numel(MODES)
    sel = use & strcmp({N.mode}, MODES{m});
    fm = NaN; ft = NaN;
    if any(sel)
        fm = sum([N(sel).eps_ls] > 0) / sum(sel);
        et = [N(sel).eps_tilt];
        if any(isfinite(et)), ft = sum(et(isfinite(et)) > 0) / sum(isfinite(et)); end
    end
    FRAC.by_mode(end+1) = struct('mode', MODES{m}, 'n_used', sum(sel), ...
        'frac_pos', fm, 'frac_pos_tilt', ft, ...
        'confounded', strcmp(MODES{m}, 'fixed-beta'));
end

% Pooled agreement: for every (rho, sig) present in BOTH modes at their
% calibrated third-axis value, does the sign agree?
FRAC.n_pairs = 0; FRAC.n_pairs_agree = 0; FRAC.n_pairs_pos_both = 0;
if numel(MODES) == 2
    for ir = 1:numel(rho_ax)
        for is = 1:numel(sig_ax)
            i1 = find(use & strcmp({N.mode}, 'fixed-beta') & ...
                      [N.rho] == rho_ax(ir) & [N.sig] == sig_ax(is) & ...
                      [N.bmult] == 1.00, 1, 'first');
            i2 = find(use & strcmp({N.mode}, 'recal-beta') & ...
                      [N.rho] == rho_ax(ir) & [N.sig] == sig_ax(is) & ...
                      [N.btarget] == btarget_cal, 1, 'first');
            if ~isempty(i1) && ~isempty(i2)
                FRAC.n_pairs = FRAC.n_pairs + 1;
                s1 = N(i1).eps_ls > 0; s2 = N(i2).eps_ls > 0;
                FRAC.n_pairs_agree    = FRAC.n_pairs_agree + (s1 == s2);
                FRAC.n_pairs_pos_both = FRAC.n_pairs_pos_both + (s1 && s2);
            end
        end
    end
end

% Admissible-region fraction: activates only when the mobility bands are
% filled AND the horizon check has been signed off.
have_band = any(isfinite([EMP.lo]) & isfinite([EMP.hi]));
MASK_ACTIVE = have_band && MASK_HORIZON_OK;
FRAC.admissible_pos   = NaN;
FRAC.n_admissible     = NaN;
FRAC.mask_active      = MASK_ACTIVE;
FRAC.mask_applied     = {};
FRAC.mask_skipped     = {};
if MASK_ACTIVE
    inmask = use;
    for e = 1:numel(EMP)
        if ~(isfinite(EMP(e).lo) && isfinite(EMP(e).hi)), continue; end
        % Map each filled band onto the per-node model statistic that is
        % actually computed here.  A band with NO per-node counterpart is
        % SKIPPED and named, never silently applied as an all-false mask:
        % htm_stay is such a case -- its model analogue (P(constrained ->
        % constrained, 2y)) is built horizon-matched in
        % main_validation_mobility.m at the calibrated point only, and is not
        % available node by node from the one-step bin chain.
        v = [];
        switch EMP(e).name
            case 'q1_stay',        v = [N.mob_ret1];
            case 'q5_stay',        v = [N.mob_retK];
            case 'shorrocks',      v = [N.mob_shorrocks];
            case 'debt_to_income', v = [N.S0];
            case 'rho_income',     v = [N.rho];
        end
        if isempty(v)
            FRAC.mask_skipped{end+1} = EMP(e).name;
            continue;
        end
        FRAC.mask_applied{end+1} = EMP(e).name;
        inmask = inmask & isfinite(v) & (v >= EMP(e).lo) & (v <= EMP(e).hi);
    end
    FRAC.n_admissible = sum(inmask);
    if FRAC.n_admissible > 0
        FRAC.admissible_pos = sum([N(inmask).eps_ls] > 0) / FRAC.n_admissible;
    end
end

% =====================================================================
% WRITE THE TABLE.
% =====================================================================
sf  = fullfile(pg0.tabdir, 'sign_map.txt');
fid = fopen(sf, 'w');
assert(fid > 0, 'cannot open %s', sf);
tee = @(varargin) sm_tee(fid, varargin{:});

tee('SIGN MAP OF THE STATIONARY TAX-DEMAND SEMI-ELASTICITY\n');
tee('eps_ls = d ln S / d tau, one-asset (certified) economy.\n\n');
tee('SETTINGS  na=%d  ne=%d  FAST=%d  RECAL=%d  modes: %s\n', ...
    pg0.na, pg0.ne, FAST, RECAL, strjoin(MODES, ', '));
tee('          r=%.6f  tau0=%.6f  D0=%.2f  dtau=%.4f  dv=%.4f  hh=%.1e\n', ...
    r_cal, tau0, D0, dtau, dv, hh);
tee('          beta at the calibrated node = %.6f  [%s]\n', pg0.beta, beta_cal_source);
tee('          nodes planned %d; converged and usable %d; unusable %d\n\n', ...
    FRAC.n_total, FRAC.n_used, FRAC.n_fail);

tee('----- AXES -----\n');
tee('%-14s %-12s %s\n', 'axis', 'status', 'values (calibrated value in brackets)');
tee('%-14s %-12s %s   [%.3f]\n', 'rho',     'POPULATED', mat2str(rho_ax, 3), rho_cal);
tee('%-14s %-12s %s   [%.3f]\n', 'sig_eps', 'POPULATED', mat2str(sig_ax, 3), sig_cal);
tee(['               the sig_eps axis is sig_eps0, the PRE-damage risk scale.\n' ...
     '               The risk channel is left ON (phi_D = %.2f, as in the\n' ...
     '               benchmark), so the realised innovation s.d. at a node is\n' ...
     '               sig_eps0*(1 + phi_D*D).  Switching phi_D off would change\n' ...
     '               the calibrated node and break the parity gate below.\n'], ...
    pg0.phi_D);
tee('%-14s %-12s %s   [%.3f]  (fixed-beta mode)\n', 'beta multiplier', 'POPULATED', ...
    mat2str(bmult_ax, 3), 1.00);
if RECAL
    tee('%-14s %-12s %s   [%.3f]  (recal-beta mode)\n', 'b_target', 'POPULATED', ...
        mat2str(btarget_ax, 3), btarget_cal);
else
    tee('%-14s %-12s %s\n', 'b_target', 'SKIPPED', ...
        'recal-beta mode not run (RECAL=false)');
end
tee('%-14s %-12s %s\n', 'lambda_adj', 'UNPOPULATED', ...
    ['two-asset parameter; the two-asset economy is UNCERTIFIED, so this ' ...
     'driver does not run it and reports no two-asset number.']);
tee('%-14s %-12s %s\n', 'iota_H', 'UNPOPULATED', ...
    ['two-asset parameter (it is a share of a fund the one-asset economy ' ...
     'does not have); same certification reason as lambda_adj.']);
tee(['NOTE: a map over rho, sig_eps and patience/leverage is NOT a map over\n' ...
     'the referee''s (lambda_adj, iota_H) plane.  The two planes are reported\n' ...
     'separately or not at all; they are not blended.\n\n']);

tee('----- EMPIRICAL RANGES (NaN SLOTS: transcribe by hand, then re-run) -----\n');
tee('%-16s %6s %8s %8s  %s\n', 'moment', 'horiz', 'lo', 'hi', 'source');
for e = 1:numel(EMP)
    tee('%-16s %6s %8s %8s  %s\n', EMP(e).name, ...
        sm_num2s(EMP(e).horizon_yrs, '%d'), sm_num2s(EMP(e).lo, '%.3f'), ...
        sm_num2s(EMP(e).hi, '%.3f'), EMP(e).src);
end
tee('MATCHING CAVEAT: the model asset is a single LIQUID asset with a\n');
tee('borrowing limit, so it maps to net worth EXCLUDING illiquid housing and\n');
tee('pensions more closely than to total net worth.  Prefer a financial-wealth\n');
tee('definition where the source offers one, and record which was used.\n');
tee('HORIZON: the model mobility column below is the ONE-STEP (annual) bin\n');
tee('chain from kv_wealth_mobility.  The moments above are 2- and 5-year.  A\n');
tee('two-year model moment is NOT the one-step bin matrix squared (the bin\n');
tee('chain is not Markov).  main_validation_mobility.m builds horizon-matched\n');
tee('moments correctly, at the calibrated point only.  MASK_HORIZON_OK=%d.\n\n', ...
    MASK_HORIZON_OK);

tee('----- PER-NODE: ELASTICITY, SIGN, AND THE EXACT SPLIT -----\n');
tee(['columns: eps_ls is the lump-sum semi-elasticity (the sign mapped).\n' ...
     'dir_ls / dst_ls are the direct policy-flow and endogenous-distribution\n' ...
     'parts of the SAME lump-sum step, per unit tax and per unit S0; they add\n' ...
     'to eps_ls_lin (the level form) up to recon.  sh_dst is the\n' ...
     'distributional share of the response.  eps_tlt, dir_tlt, dst_tlt and\n' ...
     'cov_tlt are the mean-zero regressive-tilt experiment, per unit revenue;\n' ...
     'cov_tlt is the marginal direct covariance, the term the paper''s MPC and\n' ...
     'constrained-share evidence actually disciplines.  A UNIFORM lump-sum tax\n' ...
     'has zero such covariance by construction, which is why it is reported on\n' ...
     'the tilt and not on eps_ls.\n']);
tee('%-11s %6s %6s %8s %9s %10s %4s %9s %9s %7s %10s %9s %9s %9s %3s\n', ...
    'mode', 'rho', 'sig', 'third', 'beta', 'eps_ls', 'sgn', 'dir_ls', ...
    'dst_ls', 'sh_dst', 'eps_tlt', 'dir_tlt', 'dst_tlt', 'cov_tlt', 'CAL');
for k = 1:nnode
    tee('%-11s %6.3f %6.3f %8s %9.4f %10.3f %4s %9.3f %9.3f %7.3f %10.3f %9.3f %9.3f %9.4f %3s\n', ...
        N(k).mode, N(k).rho, N(k).sig, sm_third_str(N(k)), N(k).beta, ...
        N(k).eps_ls, sm_sgn(N(k).eps_ls), N(k).dir_ls, N(k).dst_ls, ...
        N(k).share_dist_ls, N(k).eps_tilt, N(k).dir_tilt, N(k).dst_tilt, ...
        N(k).cov_tilt, sm_tern(N(k).is_cal, '<<<', ''));
end
tee('\n');

tee('----- PER-NODE: CONVERGENCE, NUMERICAL QUALITY, AND MOBILITY -----\n');
tee(['fd_stab is |eps(dtau) - eps(dtau/2)| / |eps(dtau)|: flag above 1e-2, as\n' ...
     'audit_tax_incidence does.  recon is the BLOCK B reconstruction residual\n' ...
     '(identity check, not a result).  shorr / ret1 / retK / half are the\n' ...
     'ONE-STEP bin-chain Shorrocks index, bottom- and top-bin retention and\n' ...
     'the half-life of the bin-mass movement, from kv_wealth_mobility.\n']);
tee('%-11s %6s %6s %8s %9s %9s %10s %9s %8s %7s %7s %6s %-22s\n', ...
    'mode', 'rho', 'sig', 'third', 'S0', 'cmass', 'fd_stab', 'recon', ...
    'shorr', 'ret1', 'retK', 'half', 'status');
for k = 1:nnode
    tee('%-11s %6.3f %6.3f %8s %9.4f %9.4f %10.1e %9.1e %8.3f %7.3f %7.3f %6s %-22s\n', ...
        N(k).mode, N(k).rho, N(k).sig, sm_third_str(N(k)), N(k).S0, ...
        N(k).cmass, N(k).fd_stab, N(k).recon_ls, N(k).mob_shorrocks, ...
        N(k).mob_ret1, N(k).mob_retK, sm_num2s(N(k).mob_halflife, '%d'), ...
        N(k).status);
end
n_fdflag = sum(isfinite([N.fd_stab]) & [N.fd_stab] > 1e-2);
tee('\nnodes with fd_stab > 1e-2 (quote their elasticity only after a grid\n');
tee('refinement): %d of %d.\n\n', n_fdflag, nnode);

tee('----- PARITY GATE against the certified drivers -----\n');
tee(['The elasticity and its split are defined once, by S_green plus the\n' ...
     'BLOCK B identity.  This gate compares the calibrated node of THIS map to\n' ...
     'the values decompose_tax_elasticity.m and audit_tax_incidence.m have\n' ...
     'already written, so a silent divergence between the two implementations\n' ...
     'of one object shows up here rather than in the paper.\n']);
for p = 1:numel(PAR)
    tee('  %-34s this=%12s stored=%12s gap=%10s  %s\n', PAR(p).name, ...
        sm_num2s(PAR(p).here, '%.4f'), sm_num2s(PAR(p).stored, '%.4f'), ...
        sm_num2s(PAR(p).gap, '%.2e'), PAR(p).verdict);
end
tee('\n');

tee('----- SUMMARY: THE DELIVERABLE -----\n');
tee('(A) SWEPT-BOX fraction with eps_ls > 0: %s   (over %d converged nodes)\n', ...
    sm_num2s(FRAC.swept_box_pos, '%.3f'), FRAC.n_used);
for m = 1:numel(FRAC.by_mode)
    tee('    %-11s  frac(eps_ls>0)=%s  frac(eps_tilt>0)=%s  n=%d  %s\n', ...
        FRAC.by_mode(m).mode, sm_num2s(FRAC.by_mode(m).frac_pos, '%.3f'), ...
        sm_num2s(FRAC.by_mode(m).frac_pos_tilt, '%.3f'), FRAC.by_mode(m).n_used, ...
        sm_tern(FRAC.by_mode(m).confounded, ...
                'CONFOUNDED: debt target moves with the primitive', ...
                'debt target held by recalibration'));
end
if numel(MODES) == 2
    tee('    sign agreement across modes at the calibrated third-axis value:\n');
    tee('      %d of %d (rho, sig_eps) pairs agree; %d of %d positive in BOTH.\n', ...
        FRAC.n_pairs_agree, FRAC.n_pairs, FRAC.n_pairs_pos_both, FRAC.n_pairs);
    tee(['      Following audit_tax_incidence BLOCK D: attribute a sign flip to\n' ...
         '      the primitive ONLY where it appears in both rows.\n']);
else
    tee(['    recal-beta mode was NOT run, so every fraction above is\n' ...
         '    CONFOUNDED with the debt target and must not be quoted as the\n' ...
         '    size of a sign region.  Re-run with RECAL = true.\n']);
end
tee('\n(B) ADMISSIBLE-REGION fraction with eps_ls > 0: %s\n', ...
    sm_num2s(FRAC.admissible_pos, '%.3f'));
if ~MASK_ACTIVE
    tee(['    PENDING.  The empirical ranges above are unfilled NaN slots (or\n' ...
         '    the horizon check is unsigned), so the admissible region is not\n' ...
         '    yet defined and its size cannot be reported.  This is the number\n' ...
         '    the referee asked for; (A) is not a substitute for it, because\n' ...
         '    (A) is a property of the box chosen in this file.  Until the\n' ...
         '    slots are filled the paper must report (A) with its label and\n' ...
         '    must not describe it as the measured size of the sign region.\n']);
else
    tee('    computed over %d admissible converged nodes.\n', FRAC.n_admissible);
    tee('    bands APPLIED: %s\n', sm_list2s(FRAC.mask_applied));
    tee('    bands SKIPPED (band filled, no per-node model counterpart): %s\n', ...
        sm_list2s(FRAC.mask_skipped));
    tee(['    MAPPING USED (check it): q1_stay -> bottom-bin retention,\n' ...
         '    q5_stay -> top-bin retention, shorrocks -> one-step Shorrocks\n' ...
         '    index, debt_to_income -> S0, rho_income -> rho.  The first three\n' ...
         '    are ONE-STEP model statistics; the data are 2- and 5-year.  This\n' ...
         '    mask is only as good as the horizon sign-off above.\n']);
end

tee(['\nREADING.  The sign mapped here is the sign of the LUMP-SUM\n' ...
     'semi-elasticity in the CERTIFIED ONE-ASSET economy.  It is not a\n' ...
     'statement about the two-asset economy, and the two axes the referee\n' ...
     'named that live only there (lambda_adj, iota_H) are declared unpopulated\n' ...
     'above rather than approximated.  Within each node the split shows where\n' ...
     'the response comes from: where sh_dst is near one, the paper''s MPC and\n' ...
     'constrained-share discipline is speaking to a small part of the object,\n' ...
     'and cov_tlt is the part it speaks to.  A positive fraction close to one\n' ...
     'is evidence the sign is not a knife-edge in THESE dimensions; it is not\n' ...
     'evidence about the dimensions that were not swept.\n']);

fclose(fid);
fprintf('  [saved] %s\n', sf);

META = struct('na', pg0.na, 'ne', pg0.ne, 'FAST', FAST, 'RECAL', RECAL, ...
    'modes', {MODES}, 'r_cal', r_cal, 'tau0', tau0, 'D0', D0, 'dtau', dtau, ...
    'dv', dv, 'hh', hh, 'rev', rev, 'beta_cal', pg0.beta, ...
    'beta_cal_source', beta_cal_source, 'rho_ax', rho_ax, 'sig_ax', sig_ax, ...
    'bmult_ax', bmult_ax, 'btarget_ax', btarget_ax, 'rho_cal', rho_cal, ...
    'sig_cal', sig_cal, 'btarget_cal', btarget_cal, ...
    'mask_horizon_ok', MASK_HORIZON_OK, 'elapsed_s', toc(t0));
save(fullfile(projdir, 'output', 'sign_map.mat'), ...
     'N', 'FRAC', 'EMP', 'PAR', 'META', 'MASK_ACTIVE');
fprintf('  [saved] %s\n', fullfile(projdir, 'output', 'sign_map.mat'));

% ---- figure (never fatal) ----
if MAKEFIG
    try
        fh = sm_make_figure(N, MODES, rho_ax, sig_ax, btarget_cal);
        save_all_figs(fh, 'PFig_sign_map', pg0);
        fprintf('  [saved] PFig_sign_map\n');
    catch ME
        fprintf('  [figure skipped] %s\n', ME.message);
    end
end

fprintf('\nElapsed: %.1f s\n', toc(t0));

% =========================================================================
% LOCAL FUNCTIONS
% =========================================================================
function R = sm_eval_node(nd, pg0, r, tau0, D0, dtau, dv, hh, rev)
% One node of the map.  Never throws: an unusable node returns a blank row
% with a status string, so a single infeasible corner cannot kill the run.
    R = sm_blank_row();
    R.mode    = nd.mode;
    R.rho     = nd.rho;
    R.sig     = nd.sig;
    R.bmult   = nd.bmult;
    R.btarget = nd.btarget;
    R.is_cal  = nd.is_cal;

    pg = pg0;
    pg.rho      = nd.rho;
    pg.sig_eps  = nd.sig;
    pg.sig_eps0 = nd.sig;
    % Rebuild the chain explicitly.  S_green rebuilds it itself whenever the
    % risk channel is on (phi_D > 0), from the same pg.rho and pg.sig_eps0, so
    % this is belt and braces for the phi_D = 0 case rather than a second
    % income process.
    [eG, PiD, stD] = make_income_process(pg);
    pg.eGrid = eG; pg.Pi = PiD; pg.stationary_e = stD;

    if strcmp(nd.mode, 'fixed-beta')
        pg.beta = pg0.beta * nd.bmult;
    else
        try
            [bstar, cout] = calibrate_beta(pg, r, nd.btarget, D0);
            pg.beta = bstar;
            if ~cout.converged
                R.status = 'beta-edge';
            end
        catch
            R.beta = NaN; R.status = 'beta-fail';
            return;
        end
    end
    R.beta = pg.beta;
    if pg.beta * (1 + r) >= pg.betaR_max
        R.status = 'beta-bound';
        return;
    end

    % ---- baseline ----
    [S0, o0] = S_green(r, tau0, D0, pg);
    if ~(isfinite(S0) && S0 > 0 && o0.feasible)
        R.status = sm_cat_status(R.status, 'base-infeasible');
        return;
    end
    R.S0     = S0;
    R.gini_a = o0.gini_a;
    R.cmass  = sum(o0.dist(1, :));
    if isfield(o0, 'hhdiag') && isfield(o0.hhdiag, 'err'),   R.hh_err   = o0.hhdiag.err;   end
    if isfield(o0, 'distdiag') && isfield(o0.distdiag, 'err'), R.dist_err = o0.distdiag.err; end
    if isfield(o0, 'hhdiag') && isfield(o0.hhdiag, 'euler_max_log10')
        R.euler_max_log10 = o0.hhdiag.euler_max_log10;
    end

    % ---- lump-sum step: the sign-map headline ----
    [S1, o1] = S_green(r, tau0 + dtau, D0, pg);
    if ~(isfinite(S1) && S1 > 0 && o1.feasible)
        R.status = sm_cat_status(R.status, 'ls-infeasible');
        return;
    end
    R.eps_ls     = (log(S1) - log(S0)) / dtau;
    R.eps_ls_lin = (S1 - S0) / (S0 * dtau);
    dS_pol = sum(sum((o1.polA - o0.polA) .* o0.dist));
    dS_dst = sum(sum(o1.polA .* (o1.dist - o0.dist)));
    R.dir_ls   = dS_pol / (S0 * dtau);
    R.dst_ls   = dS_dst / (S0 * dtau);
    R.recon_ls = (S1 - S0) - (dS_pol + dS_dst);
    if abs(S1 - S0) > 0
        R.share_dist_ls = dS_dst / (S1 - S0);
    end

    % ---- half-step, for finite-difference stability ----
    [S1h, o1h] = S_green(r, tau0 + dtau/2, D0, pg);
    if isfinite(S1h) && S1h > 0 && o1h.feasible
        e_half   = (log(S1h) - log(S0)) / (dtau/2);
        R.fd_stab = abs(R.eps_ls - e_half) / max(abs(R.eps_ls), eps);
    end

    % ---- mean-zero regressive tilt, and its direct covariance term ----
    % Construction copied from audit_tax_incidence BLOCK B: a uniform tax of
    % one unit of revenue plus a proportional subsidy of the same revenue, so
    % the net income change dv*(y_i - ybar) has mean zero over the baseline
    % distribution.
    pgT = pg; pgT.vartheta = -dv;
    [S1t, o1t] = S_green(r, tau0 + rev, D0, pgT);
    if isfinite(S1t) && S1t > 0 && o1t.feasible
        R.eps_tilt = (log(S1t) - log(S0)) / rev;
        dS_polT = sum(sum((o1t.polA - o0.polA) .* o0.dist));
        dS_dstT = sum(sum(o1t.polA .* (o1t.dist - o0.dist)));
        R.dir_tilt   = dS_polT / (S0 * rev);
        R.dst_tilt   = dS_dstT / (S0 * rev);
        R.recon_tilt = (S1t - S0) - (dS_polT + dS_dstT);
        if abs(S1t - S0) > 0
            R.share_dist_tilt = dS_dstT / (S1t - S0);
        end
    else
        R.status = sm_cat_status(R.status, 'tilt-infeasible');
    end

    [Sbh, obh] = S_green(r, tau0 - hh, D0, pg);
    if isfinite(Sbh) && obh.feasible
        mb    = (obh.polA - o0.polA) / hh;            % d a'/d y^net, node by node
        yeff  = o0.eGrid_eff(:);
        wy    = sum(o0.dist, 1)';
        ybar  = wy' * yeff;
        dynet = dv * (yeff - ybar);
        dS_cov = sum((mb * diag(dynet)) .* o0.dist, 'all');
        R.cov_tilt = dS_cov / (S0 * rev);
        R.Edy      = wy' * dynet;                     % mean-zero check
    else
        R.status = sm_cat_status(R.status, 'cov-skipped');
    end

    % ---- mobility, from the shared function ----
    try
        M = kv_wealth_mobility(o0.dist, o0.polA, pg.aGrid(:), o0.Pi_eff, ...
                               struct('nbin', 5, 'horizon', 200));
        R.mob_shorrocks = M.shorrocks;
        R.mob_ret1      = M.retention(1);
        R.mob_retK      = M.retention(end);
        R.mob_up1       = M.up1;
        R.mob_down1     = M.down1;
        R.mob_halflife  = M.halflife;
    catch
        R.status = sm_cat_status(R.status, 'mobility-failed');
    end

    R.conv = isfinite(R.eps_ls);
    if isempty(R.status), R.status = 'ok'; end
end

% -------------------------------------------------------------------------
function R = sm_blank_row()
% Canonical field set and order.  Every branch of sm_eval_node returns THIS
% struct, so the rows concatenate into a struct array without a field-order
% error.
    R = struct( ...
        'mode', '', 'rho', NaN, 'sig', NaN, 'bmult', NaN, 'btarget', NaN, ...
        'beta', NaN, 'is_cal', false, ...
        'S0', NaN, 'gini_a', NaN, 'cmass', NaN, ...
        'eps_ls', NaN, 'eps_ls_lin', NaN, 'dir_ls', NaN, 'dst_ls', NaN, ...
        'share_dist_ls', NaN, 'recon_ls', NaN, 'fd_stab', NaN, ...
        'eps_tilt', NaN, 'dir_tilt', NaN, 'dst_tilt', NaN, ...
        'share_dist_tilt', NaN, 'recon_tilt', NaN, 'cov_tilt', NaN, 'Edy', NaN, ...
        'mob_shorrocks', NaN, 'mob_ret1', NaN, 'mob_retK', NaN, ...
        'mob_up1', NaN, 'mob_down1', NaN, 'mob_halflife', NaN, ...
        'hh_err', NaN, 'dist_err', NaN, 'euler_max_log10', NaN, ...
        'conv', false, 'status', '');
end

% -------------------------------------------------------------------------
function s = sm_cat_status(s0, add)
    if isempty(s0), s = add; else, s = [s0 '/' add]; end
end

% -------------------------------------------------------------------------
function PAR = sm_parity_gate(projdir, N, na_here)
% Compare the calibrated node against what the certified drivers stored.
% The gate is INFORMATIONAL when the stored run used a different grid: the
% stored .mat files do not all record their na, so a gap is a prompt to check,
% not by itself a failure.
    PAR = struct('name', {}, 'here', {}, 'stored', {}, 'gap', {}, 'verdict', {});
    ic = find([N.is_cal] & [N.conv], 1, 'first');
    if isempty(ic)
        PAR(end+1) = struct('name', 'calibrated node', 'here', NaN, ...
            'stored', NaN, 'gap', NaN, ...
            'verdict', 'NOT AVAILABLE: the calibrated node did not converge');
        return;
    end
    tol = 5e-2;   % relative; the certified runs and this one may differ in na

    f1 = fullfile(projdir, 'output', 'tax_elasticity_results.mat');
    if exist(f1, 'file') == 2
        A = load(f1);
        if isfield(A, 'eps_ls')
            PAR(end+1) = sm_par_row('eps_ls vs decompose_tax_elast', ...
                N(ic).eps_ls, A.eps_ls, tol);
        end
        if isfield(A, 'eps_tilt')
            PAR(end+1) = sm_par_row('eps_tilt vs decompose_tax_elast', ...
                N(ic).eps_tilt, A.eps_tilt, tol);
        end
        if isfield(A, 'cov_perRev')
            % EXPECTED SMALL GAP, not drift: decompose_tax_elasticity measures
            % the marginal propensity at the same-revenue LEVY base
            % (vartheta = +dv), whereas audit_tax_incidence BLOCK B -- which
            % this driver follows -- measures it at the vartheta = 0 base.
            % Different base, same object to first order.  The audit row below
            % is the like-for-like comparison; this one is a cross-check.
            PAR(end+1) = sm_par_row('cov_tilt vs decompose (LEVY base)', ...
                N(ic).cov_tilt, A.cov_perRev, tol);
        end
    else
        PAR(end+1) = struct('name', 'tax_elasticity_results.mat', 'here', NaN, ...
            'stored', NaN, 'gap', NaN, ...
            'verdict', 'ABSENT: run decompose_tax_elasticity to enable this gate');
    end

    f2 = fullfile(projdir, 'output', 'audit_tax_incidence.mat');
    if exist(f2, 'file') == 2
        B = load(f2);
        if isfield(B, 'AU') && isfield(B.AU, 'blockB') && isfield(B.AU.blockB, 'per_rev')
            pr = B.AU.blockB.per_rev;
            if isfield(pr, 'pol')
                PAR(end+1) = sm_par_row('dir_tilt vs audit BLOCK B', ...
                    N(ic).dir_tilt, pr.pol, tol);
            end
            if isfield(pr, 'dist')
                PAR(end+1) = sm_par_row('dst_tilt vs audit BLOCK B', ...
                    N(ic).dst_tilt, pr.dist, tol);
            end
            if isfield(pr, 'cov')
                PAR(end+1) = sm_par_row('cov_tilt vs audit BLOCK B', ...
                    N(ic).cov_tilt, pr.cov, tol);
            end
            if isfield(pr, 'total')
                PAR(end+1) = sm_par_row('eps_tilt vs audit BLOCK B', ...
                    N(ic).eps_tilt, pr.total, tol);
            end
        end
    else
        PAR(end+1) = struct('name', 'audit_tax_incidence.mat', 'here', NaN, ...
            'stored', NaN, 'gap', NaN, ...
            'verdict', 'ABSENT: run audit_tax_incidence to enable this gate');
    end

    PAR(end+1) = struct('name', 'grid of this run (na)', 'here', na_here, ...
        'stored', NaN, 'gap', NaN, ...
        'verdict', 'stored runs do not all record na; compare grids by hand');
end

% -------------------------------------------------------------------------
function p = sm_par_row(name, here, stored, tol)
    gap = here - stored;
    if ~isfinite(here) || ~isfinite(stored)
        v = 'NOT COMPARABLE (one side missing)';
    elseif abs(gap) <= tol * max(abs(stored), 1)
        v = 'agrees within tolerance';
    else
        v = 'GAP: investigate before quoting either number';
    end
    p = struct('name', name, 'here', here, 'stored', stored, 'gap', gap, ...
               'verdict', v);
end

% -------------------------------------------------------------------------
function fh = sm_make_figure(N, MODES, rho_ax, sig_ax, btarget_cal)
% Sign of eps_ls over (rho, sig_eps) at the calibrated third-axis value, one
% panel per mode, calibrated node ringed.
    nm = numel(MODES);
    fh = figure('Name', 'PFig: sign map', 'Color', 'w', ...
                'Position', [70 70 480*nm 400]);
    for m = 1:nm
        Z = nan(numel(sig_ax), numel(rho_ax));
        for ir = 1:numel(rho_ax)
            for is = 1:numel(sig_ax)
                if strcmp(MODES{m}, 'fixed-beta')
                    j = find(strcmp({N.mode}, MODES{m}) & [N.rho] == rho_ax(ir) ...
                        & [N.sig] == sig_ax(is) & [N.bmult] == 1.00, 1, 'first');
                else
                    j = find(strcmp({N.mode}, MODES{m}) & [N.rho] == rho_ax(ir) ...
                        & [N.sig] == sig_ax(is) & [N.btarget] == btarget_cal, 1, 'first');
                end
                if ~isempty(j) && N(j).conv, Z(is, ir) = sign(N(j).eps_ls); end
            end
        end
        subplot(1, nm, m);
        imagesc(rho_ax, sig_ax, Z, [-1 1]); set(gca, 'YDir', 'normal'); box on;
        colormap(gca, [0.80 0.45 0.25; 0.90 0.90 0.90; 0.30 0.50 0.75]);
        xlabel('income persistence \rho'); ylabel('income risk \sigma_\epsilon');
        title(sprintf('sign of d ln S/d\\tau (%s)', MODES{m}));
        jc = find(strcmp({N.mode}, MODES{m}) & [N.is_cal], 1, 'first');
        if ~isempty(jc)
            hold on; plot(N(jc).rho, N(jc).sig, 'ko', 'MarkerSize', 12, ...
                          'LineWidth', 1.6);
        end
    end
end

% -------------------------------------------------------------------------
function pg = sm_rebuild_grid(pg)
    u = linspace(0, 1, pg.na)';
    pg.aGrid = -pg.abar + (pg.amax + pg.abar) * (u.^pg.acurv);
    pg.aGrid(1) = -pg.abar; pg.aGrid(end) = pg.amax;
end

% -------------------------------------------------------------------------
function s = sm_sgn(x)
    if ~isfinite(x),   s = 'n/a';
    elseif x > 0,      s = '+';
    elseif x < 0,      s = '-';
    else,              s = '0';
    end
end

% -------------------------------------------------------------------------
function s = sm_third_str(row)
    if isfinite(row.bmult)
        s = sprintf('b*%.2f', row.bmult);
    elseif isfinite(row.btarget)
        s = sprintf('bT%.2f', row.btarget);
    else
        s = '--';
    end
end

% -------------------------------------------------------------------------
function s = sm_num2s(x, fmt)
% Scalar formatter that prints a dash rather than 'NaN' for an empty slot, so
% an unfilled empirical range never reads as a measured zero.
    if isempty(x) || ~isfinite(x)
        s = '--';
    else
        s = sprintf(fmt, x);
    end
end

% -------------------------------------------------------------------------
function s = sm_list2s(c)
% Comma-joined cell of char, or an explicit '(none)'.
    if isempty(c), s = '(none)'; else, s = strjoin(c, ', '); end
end

% -------------------------------------------------------------------------
function s = sm_tern(c, a, b)
    if c, s = a; else, s = b; end
end

% -------------------------------------------------------------------------
function sm_tee(fid, varargin)
    fprintf(varargin{:}); fprintf(fid, varargin{:});
end
