function export_literature_verification(pg)
% EXPORT_LITERATURE_VERIFICATION  Machine-readable copy of the literature
% verification record (editorial-roadmap Step 7). The authoritative human
% record is appendix/LITERATURE_VERIFICATION.md (web-verification pass of
% 2026-07-03); this writer keeps a dated snapshot with the run artifacts so
% the master-status trail includes citation hygiene.
%
% USAGE: export_literature_verification(pg)   % pg from setup_params_green

    if nargin < 1, pg = setup_params_green(); end
    if ~isfolder(pg.tabdir), mkdir(pg.tabdir); end
    sf = fullfile(pg.tabdir, 'literature_verification.txt');
    fid = fopen(sf, 'w');
    if fid < 0, warning('export_literature_verification:open', 'cannot open %s', sf); return; end

    rows = { ...
    'VERIFIED', 'Kaplan, Nikolakoudis & Violante (2023, rev. 2026), NBER WP 31433 (no journal version as of 2026-07)'; ...
    'VERIFIED', 'Auclert, Rognlie & Straub (2025), Annual Review of Economics 17, 539-562 (NBER WP 32991)'; ...
    'VERIFIED', 'Hoefer (2025), Price Levels in Heterogeneous-Agent Models, arXiv:2510.26065 (working paper only)'; ...
    'VERIFIED', 'Douenne, Dyrda, Hummel & Pedroni (2025), U Toronto WP tecipa-807 (claimed CEPR DP 20820 NOT confirmable)'; ...
    'VERIFIED', 'Douenne, Hummel & Pedroni (2026), Economic Journal advance article doi:10.1093/ej/ueag006 (distinct paper)'; ...
    'VERIFIED', 'Sahuc, Smets & Vermandel (2024), Banque de France WP 977'; ...
    'VERIFIED', 'Nakov & Thomas (2026), JPE Macroeconomics ahead of print doi:10.1086/740430'; ...
    'VERIFIED', 'Garcia-Macia, Lam & Nguyen (2024), IMF WP/24/71'; ...
    'VERIFIED', 'Caselli, Lagerborg & Medas (2024), IMF WP/24/125'; ...
    'VERIFIED', 'Anyfantaki, Blix Grimaldi, Madeira, Malovana & Papadopoulos (2025), BIS WP 1275'; ...
    'VERIFIED', 'Ando, Fu, Roch & Wiriadinata (2022), IMF Staff Climate Note 2022/004'; ...
    'UNVERIFIED [u]', 'Economides & Xepapadeas (NK + climate stabilization) -- do not cite'; ...
    'UNVERIFIED [u]', 'IMF Fiscal Monitor Climate Crossroads (exact edition to pin) -- do not cite'; ...
    'UNVERIFIED [u]', 'Dees & Seghini, The Green Transition and Public Finances -- do not cite'};

    fprintf(fid, 'LITERATURE VERIFICATION SNAPSHOT (authoritative record:\n');
    fprintf(fid, 'appendix/LITERATURE_VERIFICATION.md, web pass of 2026-07-03)\n\n');
    for k = 1:size(rows, 1)
        fprintf(fid, '  %-16s %s\n', rows{k,1}, rows{k,2});
    end
    fprintf(fid, '\nProject standard: never cite an UNVERIFIED [u] item in a submission.\n');
    fclose(fid);
    fprintf('  [saved] %s\n', sf);
end
