DeltaPDR1=pdr1_s1(:,:,3,1,1)./pdr1_s1(:,:,1,1,1)-1;
DeltaPDR2=pdr2_s1(:,:,3,1,1)./pdr2_s1(:,:,1,1,1)-1;
DeltaP1=pdr1_s1(:,:,3,1,1).*div1_s1(:,:,3,1,1)./(pdr1_s1(:,:,1,1,1).*div1_s1(:,:,1,1,1))-1;
DeltaP2=pdr2_s1(:,:,3,1,1).*div2_s1(:,:,3,1,1)./(pdr2_s1(:,:,1,1,1).*div2_s1(:,:,1,1,1))-1;
DeltaD1=div1_s1(:,:,3,1,1)./div1_s1(:,:,1,1,1)-1;
DeltaD2=div2_s1(:,:,3,1,1)./div2_s1(:,:,1,1,1)-1;
DeltaRf=rf_s1(:,:,3,1,1)-rf_s1(:,:,1,1,1);
DeltaCP=ep2_s1(:,:,3,1,1)-ep1_s1(:,:,3,1,1)-(ep2_s1(:,:,1,1,1)-ep1_s1(:,:,1,1,1));

%% Code für Simulation
%time.number=(time.max-time.min)/time.delta;
time.number=(2101-time.min)/time.delta;
disp([datestr(now), ': Start Simulation of the World Economy']);
error=0;
calib.phi=2.6;
simulation.number=1000;
% Pre-allocate Matrices 
[simulation.mac,simulation.neg, simulation.d, simulation.nu, simulation.Cumulative_Emissions, simulation.Emissions, simulation.Y1, simulation.Y2,simulation.E1, simulation.E2, simulation.D1, simulation.D2, simulation.C, simulation.Output, simulation.T, simulation.Tmod, simulation.K1, simulation.K2, simulation.S, simulation.X, simulation.Y, simulation.B]=deal(NaN(simulation.number, time.number+1));
[simulation.tax,simulation.i1,simulation.i2,simulation.g1,simulation.g2,simulation.f1,simulation.f2,simulation.chi,simulation.r]=deal(NaN(simulation.number, time.number+1));
[simulation.pi_energy, simulation.pi, simulation.q1, simulation.q2, simulation.rf, simulation.ep1, simulation.ep2, simulation.cp, simulation.pdr1, simulation.pdr2]=deal(NaN(simulation.number, time.number+1));
[simulation.D1mu, simulation.D2mu,simulation.D1sigma1, simulation.D2sigma1,simulation.D1sigma2,simulation.D2sigma2,simulation.D1sigma3,simulation.D2sigma3,simulation.D1trans, simulation.D2trans, simulation.div1, simulation.div2, simulation.jumps, simulation.jump_c, simulation.g, simulation.C_Y, simulation.Cg, simulation.Cf, simulation.Ctot, simulation.Cratio]=deal(NaN(simulation.number, time.number+1));

% Allcoate starting values 
simulation.K1(:,1) = production.K0(1); 
simulation.K2(:,1) = production.K0(2); 
simulation.T(:,1) = temperature.start; 
simulation.Tmod(:,1) = temperature.start; 
simulation.S(:,1) = production.K0(2)./(production.K0(1)+production.K0(2)); 
simulation.X(:,1) = X0; % tipping 
simulation.Y(:,1) = Y0; % policy
simulation.B(:,1) = B0; % technology

%% Load solution
if strcmp(Business_as_usual,'on')==1
    load([save_data_at, 'Solution_bau\Z1_solution_', num2str(1)]);
    V=Vbau;pi_energy_s1=pi_energy_s1bau;pi_s1=pi_s1bau;mu1_s1=mu1_s1bau;mu2_s1=mu2_s1bau;ep1_s1=ep1_s1bau;ep2_s1=ep2_s1bau;pdr1_s1=pdr1_s1bau;pdr2_s1=pdr2_s1bau;rf_s1=rf_s1bau;r_s1=r_s1bau;i1_s1=i1_s1bau;i2_s1=i2_s1bau;g1_s1=g1_s1bau;g2_s1=g2_s1bau;f1_s1=f1_s1bau;f2_s1=f2_s1bau;c_s1=c_s1bau;tax_s1=tax_s1bau;Q1_s1=Q1_s1bau;Q2_s1=Q2_s1bau;
else
    load([save_data_at, 'Solution_policy\Z1_solution_', num2str(1)]);
end

%% optimal controls for start
temp_index_state    = find(simulation.S(1,1)-state.vector <0 ,1);
temp_index_temperature     = find(simulation.T(1,1)-temperature.vector <0 ,1);

temp_dif_state=(simulation.S(1,1)-state.vector(temp_index_state-1))/state.delta;
temp_dif_temperature=(simulation.T(1,1)-temperature.vector(temp_index_temperature-1))/temperature.delta;
if simulation.S(1,1)>=state.max
    temp_index_state= state.number+1;
    temp_dif_state=0;
end
if simulation.S(1,1)<state.min
    temp_index_state= 1;
    temp_dif_state=0;
end

simulation.d(:,1)     = temp_dif_state.*temp_dif_temperature.*d_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*d_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*d_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*d_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));

simulation.i1(:,1)     = temp_dif_state.*temp_dif_temperature.*i1_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*i1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*i1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*i1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.i2(:,1)     = temp_dif_state.*temp_dif_temperature.*i2_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*i2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*i2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*i2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.r(:,1)     = temp_dif_state.*temp_dif_temperature.*r_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*r_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*r_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*r_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));

simulation.f1(:,1)     = temp_dif_state.*temp_dif_temperature.*f1_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*f1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*f1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*f1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));        

simulation.f2(:,1)     = temp_dif_state.*temp_dif_temperature.*f2_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*f2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*f2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*f2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1)); 

simulation.g1(:,1)     = temp_dif_state.*temp_dif_temperature.*g1_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*g1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*g1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*g1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));  

simulation.g2(:,1)     = temp_dif_state.*temp_dif_temperature.*g2_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*g2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*g2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*g2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1)); 
        
simulation.tax(:,1)     = temp_dif_state.*temp_dif_temperature.*tax_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*tax_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*tax_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*tax_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
    
simulation.tax(:,1)     = simulation.tax(:,1).*(simulation.K1(:,1)+simulation.K2(:,1))*10^12;
    
simulation.q1(:,1)     = temp_dif_state.*temp_dif_temperature.*Q1_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*Q1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*Q1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*Q1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.q2(:,1)     = temp_dif_state.*temp_dif_temperature.*Q2_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*Q2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*Q2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*Q2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.rf(:,1) = temp_dif_state.*temp_dif_temperature.*rf_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*rf_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*rf_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*rf_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.pdr1(:,1) =         (temp_dif_state.*temp_dif_temperature.*pdr1_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*pdr1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*pdr1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*pdr1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1)))^(-1);
  
simulation.pdr2(:,1) =         (temp_dif_state.*temp_dif_temperature.*pdr2_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*pdr2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*pdr2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*pdr2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1)))^(-1);
        
simulation.ep1(:,1) =         temp_dif_state.*temp_dif_temperature.*ep1_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*ep1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*ep1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*ep1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.ep2(:,1) =         temp_dif_state.*temp_dif_temperature.*ep2_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*ep2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*ep2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*ep2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.pi(:,1) =         temp_dif_state.*temp_dif_temperature.*pi_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*pi_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*pi_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*pi_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.pi(:,1) =         temp_dif_state.*temp_dif_temperature.*pi_energy_s1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*pi_energy_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*pi_energy_s1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*pi_energy_s1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
        
simulation.E1(:,1)=(pref.kappa(1,1).*(simulation.g1(:,1).*simulation.K1(:,1)).^pref.rho(1)+pref.kappa(2,1).*(simulation.f1(:,1).*simulation.K1(:,1)).^pref.rho(1)).^(1/pref.rho(1));
simulation.E2(:,1)=(pref.kappa(1,2).*(simulation.g2(:,1).*simulation.K2(:,1)).^pref.rho(2)+pref.kappa(2,2).*(simulation.f2(:,1).*simulation.K2(:,1)).^pref.rho(2)).^(1/pref.rho(2));
simulation.Y1(:,1)=production.A(1).*simulation.K1(:,1).^(1-production.eta(1)).*simulation.E1(:,1).^production.eta(1).*D(simulation.T(:,1),simulation.Y(1,1),simulation.X(1,1)-1);
simulation.Y2(:,1)=production.A(2).*simulation.K2(:,1).^(1-production.eta(2)).*simulation.E2(:,1).^production.eta(2).*D(simulation.T(:,1),simulation.Y(1,1),simulation.X(1,1)-1);
simulation.D1(:,1)=simulation.Y1(:,1)-simulation.i1(:,1).*simulation.K1(:,1)-production.b(1,1).*simulation.g1(:,1).*simulation.K1(:,1)-production.b(2,1).*simulation.f1(:,1).*simulation.K1(:,1);
simulation.D2(:,1)=simulation.Y2(:,1)-simulation.i2(:,1).*simulation.K2(:,1)-production.b(1,1).*simulation.g2(:,1).*simulation.K2(:,1)-production.b(2,1).*simulation.f2(:,1).*simulation.K2(:,1);
simulation.C(:,1)=simulation.D1(:,1)+simulation.D2(:,1);
simulation.div1(:,1)=1;
simulation.div2(:,1)=1;
simulation.Output(:,1) =simulation.Y1(:,1)+simulation.Y2(:,1);
simulation.C_Y(:,1)=simulation.C(:,1)./simulation.Output(:,1);  
simulation.Cumulative_Emissions(:,1)=185;


simulation.pi_energy(:,1) =  (simulation.g1(:,1).*simulation.K1(:,1) + simulation.g2(:,1).*simulation.K2(:,1))./(simulation.g1(:,1).*simulation.K1(:,1) + simulation.g2(:,1).*simulation.K2(:,1) + simulation.f1(:,1).*simulation.K1(:,1) + simulation.f2(:,1).*simulation.K2(:,1));
simulation.Cg(:,1)=(simulation.g1(:,1).*simulation.K1(:,1) + simulation.g2(:,1).*simulation.K2(:,1)).*production.b(1,1)*cost_scaling(1,production.S0);
simulation.Cf(:,1)=(simulation.f1(:,1).*simulation.K1(:,1) + simulation.f2(:,1).*simulation.K2(:,1)).*production.b(2);
simulation.Ctot(:,1)=simulation.Cg(:,1)+simulation.Cf(:,1);
simulation.Cratio(:,1)=simulation.Ctot(:,1)./simulation.Output(:,1);
simulation.cp(:,1)=simulation.ep2(:,1)-simulation.ep1(:,1);


% Dividends
simulation.D1mu(:,1)=temp_dif_state.*temp_dif_temperature.*D1.mu(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.mu(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.mu(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.mu(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D2mu(:,1)=temp_dif_state.*temp_dif_temperature.*D2.mu(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.mu(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.mu(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.mu(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));

simulation.D1sigma1(:,1)=temp_dif_state.*temp_dif_temperature.*D1.sigma1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.sigma1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.sigma1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.sigma1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D1sigma2(:,1)=temp_dif_state.*temp_dif_temperature.*D1.sigma2(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.sigma2(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.sigma2(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.sigma2(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D1sigma3(:,1)=temp_dif_state.*temp_dif_temperature.*D1.sigma3(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.sigma3(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.sigma3(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.sigma3(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));

simulation.D2sigma1(:,1)=temp_dif_state.*temp_dif_temperature.*D2.sigma1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.sigma1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.sigma1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.sigma1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D2sigma2(:,1)=temp_dif_state.*temp_dif_temperature.*D2.sigma2(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.sigma2(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.sigma2(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.sigma2(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D2sigma3(:,1)=temp_dif_state.*temp_dif_temperature.*D2.sigma3(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.sigma3(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.sigma3(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.sigma3(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
%if simulation.Y(1,1)==1
simulation.D1trans(:,1)=temp_dif_state.*temp_dif_temperature.*D1.z13(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.z13(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.z13(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.z13(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D2trans(:,1)=temp_dif_state.*temp_dif_temperature.*D2.z13(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.z13(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.z13(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.z13(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
%else
%    simulation.D1trans(:,1)=0;
%    simulation.D2trans(:,1)=0;
%end
%% Monte-Carlo Simulation
for temp_index_t=2:time.number
    if strcmp(Business_as_usual,'on')==1
        load([save_data_at, 'Solution_bau\Z1_solution_', num2str(temp_index_t)]);
        V=Vbau;pi_energy_s1=pi_energy_s1bau;pi_s1=pi_s1bau;mu1_s1=mu1_s1bau;mu2_s1=mu2_s1bau;ep1_s1=ep1_s1bau;ep2_s1=ep2_s1bau;pdr1_s1=pdr1_s1bau;pdr2_s1=pdr2_s1bau;rf_s1=rf_s1bau;r_s1=r_s1bau;i1_s1=i1_s1bau;i2_s1=i2_s1bau;g1_s1=g1_s1bau;g2_s1=g2_s1bau;f1_s1=f1_s1bau;f2_s1=f2_s1bau;c_s1=c_s1bau;tax_s1=tax_s1bau;Q1_s1=Q1_s1bau;Q2_s1=Q2_s1bau;
    else
        load([save_data_at, 'Solution_policy\Z1_solution_', num2str(temp_index_t)]);
    end
    
    for  temp_counter=1:simulation.number
        %% Emissions
        simulation.mac(temp_counter,temp_index_t-1) = (NET.a(1)*simulation.S(temp_counter,temp_index_t-1).^NET.a(2)  +NET.a(3)*NET.a(4)*simulation.S(temp_counter,temp_index_t-1).^NET.a(5)  .*exp(NET.a(3)*simulation.S(temp_counter,temp_index_t-1).^NET.a(6)*simulation.d(temp_counter,temp_index_t-1))).*(simulation.K1(temp_counter,temp_index_t-1)+simulation.K2(temp_counter,temp_index_t-1))*10^12;
        simulation.Emissions(temp_counter,temp_index_t-1) = temperature.p(temp_index_t-1).*(simulation.f1(temp_counter,temp_index_t-1)*(1-simulation.S(temp_counter,temp_index_t-1))+simulation.f2(temp_counter,temp_index_t-1)*simulation.S(temp_counter,temp_index_t-1));
        simulation.neg(temp_counter,temp_index_t-1) = simulation.d(temp_counter,temp_index_t-1);
        simulation.Cumulative_Emissions(temp_counter,temp_index_t)=simulation.Cumulative_Emissions(temp_counter,temp_index_t-1)+simulation.Emissions(temp_counter,temp_index_t-1)*time.delta;
        
        %% Temperature
        simulation.T(temp_counter,temp_index_t)=simulation.T(temp_counter,temp_index_t-1)...
            + temperature.tcre*tcre_scaling(simulation.X(temp_counter,temp_index_t-1)).*simulation.Emissions(temp_counter,temp_index_t-1)*time.delta ...
            - temperature.tcre*tcre_scaling(simulation.X(temp_counter,temp_index_t-1)).*simulation.neg(temp_counter,temp_index_t-1)*time.delta ...
            + simulation.T(temp_counter,temp_index_t-1) * temperature.sigma * dWtau(temp_counter,temp_index_t-1);

        simulation.T(temp_counter,temp_index_t)=max(0.01,simulation.T(temp_counter,temp_index_t));

        %% Disaster Risk
        jump_temp=-1/intensity.lambda*log(U(temp_counter,temp_index_t-1));
        if jump_temp<=time.delta
            simulation.jump(temp_counter,temp_index_t-1)=Z(temp_counter,temp_index_t-1);
        else
            simulation.jump(temp_counter,temp_index_t-1)=0;
        end
        %% Climate Disaster Risk
        jump_climate_temp=-1/(climate.lambda1*simulation.T(temp_counter,temp_index_t-1))*log(Uc(temp_counter,temp_index_t-1));
        if jump_climate_temp<=time.delta
            simulation.jump_c(temp_counter,temp_index_t-1)=Zc(temp_counter,temp_index_t-1);
        else
            simulation.jump_c(temp_counter,temp_index_t-1)=0;
        end
        %% Transition Risk
        if strcmp(Policy,'on')==1
            if simulation.Y(temp_counter,temp_index_t-1)==1
                jump_temp12=-1/lambda_pol(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),1,2)*log(U_pol_backward(temp_counter,temp_index_t-1));
                jump_temp13=-1/lambda_pol(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),1,3)*log(U_pol_forward(temp_counter,temp_index_t-1));
                if jump_temp12<=time.delta && jump_temp13>time.delta
                    simulation.Y(temp_counter,temp_index_t)=2;
                elseif jump_temp13<=time.delta
                    simulation.Y(temp_counter,temp_index_t)=3;
                    indicatior13=1;
                else
                    simulation.Y(temp_counter,temp_index_t)=1;
                    indicatior13=0;
                end
            elseif simulation.Y(temp_counter,temp_index_t-1)==2
                jump_temp21=-1/lambda_pol(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),2,1)*log(U_pol_backward(temp_counter,temp_index_t-1));
                jump_temp23=-1/lambda_pol(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),2,3)*log(U_pol_forward(temp_counter,temp_index_t-1));
                if jump_temp21<=time.delta && jump_temp23>time.delta
                    simulation.Y(temp_counter,temp_index_t)=1;
                elseif jump_temp23<=time.delta
                    simulation.Y(temp_counter,temp_index_t)=3;
                else
                    simulation.Y(temp_counter,temp_index_t)=2;
                end
            elseif simulation.Y(temp_counter,temp_index_t-1)==3
                jump_temp32=-1/lambda_pol(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),3,2)*log(U_pol_backward(temp_counter,temp_index_t-1));
                jump_temp31=-1/lambda_pol(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),3,1)*log(U_pol_forward(temp_counter,temp_index_t-1));
                if jump_temp32<=time.delta && jump_temp31>time.delta
                    simulation.Y(temp_counter,temp_index_t)=2;
                elseif jump_temp31<=time.delta
                    simulation.Y(temp_counter,temp_index_t)=1;
                else
                    simulation.Y(temp_counter,temp_index_t)=3;
                end
            end
        else
            simulation.Y(temp_counter,temp_index_t)=simulation.Y(temp_counter,temp_index_t-1);
        end
        %% Tipping Risk
        if strcmp(Tipping,'on')==1
            if simulation.X(temp_counter,temp_index_t-1)==1
                jump_temp12=-1/lambda_tipp(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),simulation.Y(temp_counter,temp_index_t-1),1)*log(U_tipp(temp_counter,temp_index_t-1));
                jump_temp13=-1/lambda_tipp(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),simulation.Y(temp_counter,temp_index_t-1),1)*log(U_tipp2(temp_counter,temp_index_t-1));
                if jump_temp12<=time.delta && jump_temp13>time.delta
                    simulation.X(temp_counter,temp_index_t)=2;
                elseif jump_temp13<=time.delta
                    simulation.X(temp_counter,temp_index_t)=3;
                else
                    simulation.X(temp_counter,temp_index_t)=1;
                end
            elseif simulation.X(temp_counter,temp_index_t-1)==2
                jump_temp23=-1/lambda_tipp(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),simulation.Y(temp_counter,temp_index_t-1),2)*log(U_tipp(temp_counter,temp_index_t-1));
                if  jump_temp23<=time.delta
                    simulation.X(temp_counter,temp_index_t)=3;
                else
                    simulation.X(temp_counter,temp_index_t)=2;
                end
            elseif simulation.X(temp_counter,temp_index_t-1)==3
                    simulation.X(temp_counter,temp_index_t)=3;
            end
        else
            simulation.X(temp_counter,temp_index_t)=simulation.X(temp_counter,temp_index_t-1);
        end
        %% Technological Breakthrough
        if simulation.B(temp_counter,temp_index_t-1)<breakthrough.number+1
            jump_temp=-1/lambda_breakthrough(simulation.T(temp_counter,temp_index_t-1),simulation.S(temp_counter,temp_index_t-1),simulation.Y(temp_counter,temp_index_t-1),simulation.X(temp_counter,temp_index_t-1),simulation.B(temp_counter,temp_index_t-1))*log(U_bt(temp_counter,temp_index_t-1));
            if jump_temp<=time.delta && strcmp(Breakthrough,'on')==1
                simulation.B(temp_counter,temp_index_t)=simulation.B(temp_counter,temp_index_t-1)+1;
            else
                simulation.B(temp_counter,temp_index_t)=simulation.B(temp_counter,temp_index_t-1);
            end
        else
            simulation.B(temp_counter,temp_index_t)=breakthrough.number+1;
        end

        %% Green capital
        simulation.K1(temp_counter,temp_index_t)=simulation.K1(temp_counter,temp_index_t-1)*exp(...
            (-production.delta(1)+simulation.i1(temp_counter,temp_index_t-1)-production.costs(simulation.i1(temp_counter,temp_index_t-1),1)+simulation.r(temp_counter,temp_index_t-1)-0.5*reallocation.kappa*simulation.r(temp_counter,temp_index_t-1)^2)*time.delta ...
            + production.sigma(1).*dW1(temp_counter,temp_index_t-1)...
            - simulation.jump(temp_counter,temp_index_t-1)...
            - simulation.jump_c(temp_counter,temp_index_t-1));
        
        %% Brown capital
        simulation.K2(temp_counter,temp_index_t)=simulation.K2(temp_counter,temp_index_t-1)*exp(...
            + (-production.delta(2)+simulation.i2(temp_counter,temp_index_t-1)-production.costs(simulation.i2(temp_counter,temp_index_t-1),2)-simulation.r(temp_counter,temp_index_t-1).*(1-simulation.S(temp_counter,temp_index_t-1))/simulation.S(temp_counter,temp_index_t-1))*time.delta ...
            + production.sigma(2).*(production.rho12*dW1(temp_counter,temp_index_t-1)+sqrt(1-production.rho12^2)*dW2(temp_counter,temp_index_t-1))...
            - simulation.jump(temp_counter,temp_index_t-1)...
            - simulation.jump_c(temp_counter,temp_index_t-1));

        %% Green Dividends
        simulation.div1(temp_counter,temp_index_t)=simulation.div1(temp_counter,temp_index_t-1)*exp(...
            (-production.delta(1)+simulation.i1(temp_counter,temp_index_t-1)-production.costs(simulation.i1(temp_counter,temp_index_t-1),1)+simulation.r(temp_counter,temp_index_t-1)-0.5*reallocation.kappa*simulation.r(temp_counter,temp_index_t-1)^2)*time.delta ...
            +simulation.D1sigma1(temp_counter,temp_index_t-1)*dW1(temp_counter,temp_index_t-1)...
            +simulation.D1sigma2(temp_counter,temp_index_t-1)*dW2(temp_counter,temp_index_t-1)...
            +simulation.D1sigma3(temp_counter,temp_index_t-1)*dWtau(temp_counter,temp_index_t-1)...
            +((1-simulation.jump(temp_counter,temp_index_t-1)).^calib.phi-1)...
            +((1-simulation.jump_c(temp_counter,temp_index_t-1)).^calib.phi-1)...
            -indicatior13*simulation.D1trans(temp_counter,temp_index_t-1));
       
        %% Brown Dividends
        simulation.div2(temp_counter,temp_index_t)=simulation.div2(temp_counter,temp_index_t-1)*exp(...
            + (-production.delta(2)+simulation.i2(temp_counter,temp_index_t-1)-production.costs(simulation.i2(temp_counter,temp_index_t-1),2)-simulation.r(temp_counter,temp_index_t-1).*(1-simulation.S(temp_counter,temp_index_t-1))/simulation.S(temp_counter,temp_index_t-1))*time.delta ...
            +simulation.D2sigma1(temp_counter,temp_index_t-1)*dW1(temp_counter,temp_index_t-1)...
            +simulation.D2sigma2(temp_counter,temp_index_t-1)*dW2(temp_counter,temp_index_t-1)...
            +simulation.D2sigma3(temp_counter,temp_index_t-1)*dWtau(temp_counter,temp_index_t-1)...
            +((1-simulation.jump(temp_counter,temp_index_t-1)).^calib.phi-1)...
            +((1-simulation.jump_c(temp_counter,temp_index_t-1)).^calib.phi-1)...
            -indicatior13*simulation.D2trans(temp_counter,temp_index_t-1));

        %% State
        simulation.S(temp_counter,temp_index_t)=max(0.01,simulation.K2(temp_counter,temp_index_t)/(simulation.K1(temp_counter,temp_index_t)+simulation.K2(temp_counter,temp_index_t)));
        
        %% Investment Strategy
        temp_index_state    = find(simulation.S(temp_counter,temp_index_t)-state.vector <0 ,1);
        temp_index_temperature     = find(simulation.T(temp_counter,temp_index_t)-temperature.vector <0 ,1);
        
        if simulation.S(temp_counter,temp_index_t)<state.vector(1)
            temp_dif_state=0;
        else
            temp_dif_state=(simulation.S(temp_counter,temp_index_t)-state.vector(temp_index_state-1))/state.delta;
            temp_dif_temperature=(simulation.T(temp_counter,temp_index_t)-temperature.vector(temp_index_temperature-1))/temperature.delta;
        end
        if simulation.T(temp_counter,temp_index_t)>temperature.max
            temp_index_temperature= temperature.number+1;
            temp_dif_temperature=0;
        end
        if simulation.T(temp_counter,temp_index_t)<temperature.min
            temp_index_temperature= 1;
            temp_dif_temperature=0;
        end
        if simulation.S(temp_counter,temp_index_t)>state.max
            temp_index_state= state.number+1;
            temp_dif_state=0;
        end
        if simulation.S(temp_counter,temp_index_t)<state.min
            temp_index_state= 1;
            temp_dif_state=0;
        end
        simulation.d(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*d_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*d_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*d_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*d_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.i1(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*i1_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*i1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*i1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*i1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.i2(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*i2_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*i2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*i2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*i2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.r(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*r_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*r_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*r_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*r_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.f1(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*f1_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*f1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*f1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*f1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.f2(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*f2_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*f2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*f2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*f2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.g1(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*g1_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*g1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*g1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*g1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.g2(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*g2_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*g2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*g2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*g2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.tax(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*tax_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*tax_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*tax_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*tax_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.tax(temp_counter,temp_index_t)     =simulation.tax(temp_counter,temp_index_t)*(simulation.K1(temp_counter,temp_index_t)+simulation.K2(temp_counter,temp_index_t))*10^12;
        
        simulation.q1(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*Q1_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*Q1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*Q1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*Q1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.q2(temp_counter,temp_index_t)     = temp_dif_state.*temp_dif_temperature.*Q2_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*Q2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*Q2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*Q2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.rf(temp_counter,temp_index_t) = temp_dif_state.*temp_dif_temperature.*rf_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*rf_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*rf_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*rf_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.pdr1(temp_counter,temp_index_t) =         (temp_dif_state.*temp_dif_temperature.*pdr1_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*pdr1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*pdr1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*pdr1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t)))^(-1);
        
        simulation.pdr2(temp_counter,temp_index_t) =         (temp_dif_state.*temp_dif_temperature.*pdr2_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*pdr2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*pdr2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*pdr2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t)))^(-1);
        
        simulation.ep1(temp_counter,temp_index_t) =         temp_dif_state.*temp_dif_temperature.*ep1_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*ep1_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*ep1_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*ep1_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.ep2(temp_counter,temp_index_t) =         temp_dif_state.*temp_dif_temperature.*ep2_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*ep2_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*ep2_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*ep2_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        simulation.pi(temp_counter,temp_index_t) =         temp_dif_state.*temp_dif_temperature.*pi_s1(temp_index_state,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*pi_s1(temp_index_state-1,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +(1-temp_dif_state).*temp_dif_temperature.*pi_s1(temp_index_state-1,temp_index_temperature,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t))...
            +temp_dif_state.*(1-temp_dif_temperature).*pi_s1(temp_index_state,temp_index_temperature-1,simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t),simulation.B(temp_counter,temp_index_t));
        
        % Dividends
simulation.D1mu(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D1.mu(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.mu(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.mu(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.mu(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D2mu(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D2.mu(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.mu(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.mu(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.mu(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));

simulation.D1sigma1(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D1.sigma1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.sigma1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.sigma1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.sigma1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D1sigma2(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D1.sigma2(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.sigma2(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.sigma2(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.sigma2(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D1sigma3(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D1.sigma3(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.sigma3(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.sigma3(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.sigma3(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));

simulation.D2sigma1(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D2.sigma1(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.sigma1(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.sigma1(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.sigma1(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D2sigma2(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D2.sigma2(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.sigma2(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.sigma2(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.sigma2(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D2sigma3(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D2.sigma3(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.sigma3(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.sigma3(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.sigma3(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
%if simulation.Y(1,1)==1
simulation.D1trans(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D1.z13(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D1.z13(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D1.z13(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D1.z13(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
simulation.D2trans(temp_counter,temp_index_t)=temp_dif_state.*temp_dif_temperature.*D2.z13(temp_index_state,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*(1-temp_dif_temperature).*D2.z13(temp_index_state-1,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +(1-temp_dif_state).*temp_dif_temperature.*D2.z13(temp_index_state-1,temp_index_temperature,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1))...
            +temp_dif_state.*(1-temp_dif_temperature).*D2.z13(temp_index_state,temp_index_temperature-1,simulation.Y(1,1),simulation.X(1,1),simulation.B(1,1));
%else
%    simulation.D1trans(temp_counter,temp_index_t)=0;
%    simulation.D2trans(temp_counter,temp_index_t)=0;
%end
% absolute quantities
        simulation.E1(temp_counter,temp_index_t)=(pref.kappa(1,1).*(simulation.g1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t)).^pref.rho(1)+pref.kappa(2,1).*(simulation.f1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t)).^pref.rho(1)).^(1/pref.rho(1));
        simulation.E2(temp_counter,temp_index_t)=(pref.kappa(1,2).*(simulation.g2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t)).^pref.rho(2)+pref.kappa(2,2).*(simulation.f2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t)).^pref.rho(2)).^(1/pref.rho(2));
        simulation.Y1(temp_counter,temp_index_t)=production.A(1).*simulation.K1(temp_counter,temp_index_t).^(1-production.eta(1)).*simulation.E1(temp_counter,temp_index_t).^production.eta(1).*D(simulation.T(temp_counter,temp_index_t),simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t));
        simulation.Y2(temp_counter,temp_index_t)=production.A(2).*simulation.K2(temp_counter,temp_index_t).^(1-production.eta(2)).*simulation.E2(temp_counter,temp_index_t).^production.eta(2).*D(simulation.T(temp_counter,temp_index_t),simulation.Y(temp_counter,temp_index_t),simulation.X(temp_counter,temp_index_t));
        simulation.D1(temp_counter,temp_index_t)=simulation.Y1(temp_counter,temp_index_t)-simulation.i1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t)-production.b(1,temp_index_t).*simulation.g1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t)-production.b(2,temp_index_t).*simulation.f1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t);
        simulation.D2(temp_counter,temp_index_t)=simulation.Y2(temp_counter,temp_index_t)-simulation.i2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t)-production.b(1,temp_index_t).*simulation.g2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t)-production.b(2,temp_index_t).*simulation.f2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t);
        simulation.Output(temp_counter,temp_index_t) =simulation.Y1(temp_counter,temp_index_t)+simulation.Y2(temp_counter,temp_index_t);
        simulation.C(temp_counter,temp_index_t)=simulation.D1(temp_counter,temp_index_t)+simulation.D2(temp_counter,temp_index_t);
        simulation.pi_energy(temp_counter,temp_index_t) =  (simulation.g1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t) + simulation.g2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t))/(simulation.g1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t) + simulation.g2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t) + simulation.f1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t) + simulation.f2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t));
        simulation.Cg(temp_counter,temp_index_t)=(simulation.g1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t) + simulation.g2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t)).*production.b(1,temp_index_t)*cost_scaling(1,simulation.S(temp_counter,temp_index_t));
        simulation.Cf(temp_counter,temp_index_t)=(simulation.f1(temp_counter,temp_index_t).*simulation.K1(temp_counter,temp_index_t) + simulation.f2(temp_counter,temp_index_t).*simulation.K2(temp_counter,temp_index_t)).*production.b(2);
        simulation.Ctot(temp_counter,temp_index_t)=simulation.Cg(temp_counter,temp_index_t)+simulation.Cf(temp_counter,temp_index_t);
        simulation.Cratio(temp_counter,temp_index_t)=simulation.Ctot(temp_counter,temp_index_t)./simulation.Output(temp_counter,temp_index_t);
        % relative quantities
        simulation.g(temp_counter,temp_index_t-1)=log(simulation.Output(temp_counter,temp_index_t)./simulation.Output(temp_counter,temp_index_t-1));
        %simulation.g(temp_counter,temp_index_t-1)=log(simulation.C(temp_counter,temp_index_t)./simulation.C(temp_counter,temp_index_t-1));
        simulation.nu(temp_counter,temp_index_t)=temperature.p(temp_index_t).*simulation.S(temp_counter,temp_index_t)./(simulation.K1(temp_counter,temp_index_t)+simulation.K2(temp_counter,temp_index_t));
        simulation.C_Y(temp_counter,temp_index_t)=simulation.C(temp_counter,temp_index_t)./simulation.Output(temp_counter,temp_index_t);
        simulation.cp(temp_counter,temp_index_t)=simulation.ep2(temp_counter,temp_index_t)-simulation.ep1(temp_counter,temp_index_t);
    end
end

%% Testing by temperature in 2100
temperature_state1=simulation.T(:,81);
temperature_state1(temperature_state1<=2.5)=NaN;
temperature_state1(temperature_state1>2.5)=1;
no_1=nansum(temperature_state1);
bau_percent=no_1/simulation.number;

temperature_state2=simulation.T(:,81);
temperature_state2(temperature_state2>2.5)=NaN;
temperature_state2(temperature_state2<=1.8)=NaN;
temperature_state2(isnan(temperature_state2)==0)=1;
no_2=nansum(temperature_state2);
opt_percent=no_2/simulation.number;

temperature_state3=simulation.T(:,81);
temperature_state3(temperature_state3>1.8)=NaN;
temperature_state3(temperature_state3<=1.8)=1;
no_3=nansum(temperature_state3);
lim_percent=no_3/simulation.number;
disp([lim_percent opt_percent bau_percent]);

table_intensities=[lambda_pol(temperature.start ,production.S0,1,2), lambda_pol(temperature.start ,production.S0,1,3), lambda_pol(temperature.start ,production.S0,2,3), lambda_pol(temperature.start ,production.S0,2,1), lambda_pol(temperature.start ,production.S0,3,1), lambda_pol(temperature.start ,production.S0,3,2);
    lambda_pol(2 ,production.S0,1,2), lambda_pol(2 ,production.S0,1,3), lambda_pol(2 ,production.S0,2,3), lambda_pol(2 ,production.S0,2,1), lambda_pol(2 ,production.S0,3,1), lambda_pol(2 ,production.S0,3,2);
    lambda_pol(temperature.start ,0.1,1,2), lambda_pol(temperature.start ,0.1,1,3), lambda_pol(temperature.start ,0.1,2,3), lambda_pol(temperature.start ,0.1,2,1), lambda_pol(temperature.start ,0.1,3,1), lambda_pol(temperature.start ,0.1,3,2);
    lambda_pol(2 ,0.1,1,2), lambda_pol(2 ,0.1,1,3), lambda_pol(2 ,0.1,2,3), lambda_pol(2 ,0.1,2,1), lambda_pol(2 ,0.1,3,1), lambda_pol(2 ,0.1,3,2);
    ];