chi1.d(:,:,policy_counter,tipping_counter,breakthrough_counter)=chi1_s1(:,:,policy_counter,tipping_counter,breakthrough_counter);
chi2.d(:,:,policy_counter,tipping_counter,breakthrough_counter)=chi2_s1(:,:,policy_counter,tipping_counter,breakthrough_counter);
chi1.dt(:,:,policy_counter,tipping_counter,breakthrough_counter)=(chi1_s1Old(:,:,policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(:,:,policy_counter,tipping_counter,breakthrough_counter))./time.delta;
chi2.dt(:,:,policy_counter,tipping_counter,breakthrough_counter)=(chi2_s1Old(:,:,policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(:,:,policy_counter,tipping_counter,breakthrough_counter))./time.delta;
chi1.ds(2:state.number,:,policy_counter,tipping_counter,breakthrough_counter)=(chi1_s1(3:(state.number+1),:,policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(1:(state.number-1),:,policy_counter,tipping_counter,breakthrough_counter))./(2.*state.delta);
chi2.ds(2:state.number,:,policy_counter,tipping_counter,breakthrough_counter)=(chi2_s1(3:(state.number+1),:,policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(1:(state.number-1),:,policy_counter,tipping_counter,breakthrough_counter))./(2.*state.delta);
chi1.ds(1,:,policy_counter,tipping_counter,breakthrough_counter)=(-3.*chi1_s1(1,:,policy_counter,tipping_counter,breakthrough_counter)+4.*chi1_s1(2,:,policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(3,:,policy_counter,tipping_counter,breakthrough_counter))./(2.*state.delta);
chi2.ds(1,:,policy_counter,tipping_counter,breakthrough_counter)=(-3.*chi2_s1(1,:,policy_counter,tipping_counter,breakthrough_counter)+4.*chi2_s1(2,:,policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(3,:,policy_counter,tipping_counter,breakthrough_counter))./(2.*state.delta);
chi1.ds(state.number+1,:,policy_counter,tipping_counter,breakthrough_counter)=(3.*chi1_s1(state.number+1,:,policy_counter,tipping_counter,breakthrough_counter)-4.*chi1_s1(state.number,:,policy_counter,tipping_counter,breakthrough_counter)+chi1_s1(state.number-1,:,policy_counter,tipping_counter,breakthrough_counter))./(2.*state.delta);
chi2.ds(state.number+1,:,policy_counter,tipping_counter,breakthrough_counter)=(3.*chi2_s1(state.number+1,:,policy_counter,tipping_counter,breakthrough_counter)-4.*chi2_s1(state.number,:,policy_counter,tipping_counter,breakthrough_counter)+chi2_s1(state.number-1,:,policy_counter,tipping_counter,breakthrough_counter))./(2.*state.delta);
chi1.dtau(:,2:temperature.number,policy_counter,tipping_counter,breakthrough_counter)=(chi1_s1(:,3:(temperature.number+1),policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(:,1:(temperature.number-1),policy_counter,tipping_counter,breakthrough_counter))./(2.*temperature.delta);
chi1.dtau(:,1,policy_counter,tipping_counter,breakthrough_counter)=(-3.*chi1_s1(:,1,policy_counter,tipping_counter,breakthrough_counter)+4.*chi1_s1(:,2,policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(:,3,policy_counter,tipping_counter,breakthrough_counter))./(2.*temperature.delta);
chi1.dtau(:,temperature.number+1,policy_counter,tipping_counter,breakthrough_counter)=(3.*chi1_s1(:,temperature.number+1,policy_counter,tipping_counter,breakthrough_counter)-4.*chi1_s1(:,temperature.number,policy_counter,tipping_counter,breakthrough_counter)+chi1_s1(:,temperature.number-1,policy_counter,tipping_counter,breakthrough_counter))./(2.*temperature.delta);
chi2.dtau(:,2:temperature.number,policy_counter,tipping_counter,breakthrough_counter)=(chi2_s1(:,3:(temperature.number+1),policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(:,1:(temperature.number-1),policy_counter,tipping_counter,breakthrough_counter))./(2.*temperature.delta);
chi2.dtau(:,1,policy_counter,tipping_counter,breakthrough_counter)=(-3.*chi2_s1(:,1,policy_counter,tipping_counter,breakthrough_counter)+4.*chi2_s1(:,2,policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(:,3,policy_counter,tipping_counter,breakthrough_counter))./(2.*temperature.delta);
chi2.dtau(:,temperature.number+1,policy_counter,tipping_counter,breakthrough_counter)=(3.*chi2_s1(:,temperature.number+1,policy_counter,tipping_counter,breakthrough_counter)-4.*chi2_s1(:,temperature.number,policy_counter,tipping_counter,breakthrough_counter)+chi2_s1(:,temperature.number-1,policy_counter,tipping_counter,breakthrough_counter))./(2.*temperature.delta);    
chi1.dss(2:state.number,:,policy_counter,tipping_counter,breakthrough_counter)=(chi1_s1(3:(state.number+1),:,policy_counter,tipping_counter,breakthrough_counter)-2*chi1_s1(2:state.number,:,policy_counter,tipping_counter,breakthrough_counter)+chi1_s1(1:(state.number-1),:,policy_counter,tipping_counter,breakthrough_counter))./state.delta^2;
chi1.dss(1,:,policy_counter,tipping_counter,breakthrough_counter) =(2.*chi1_s1(1,:,policy_counter,tipping_counter,breakthrough_counter)-5.*chi1_s1(2,:,policy_counter,tipping_counter,breakthrough_counter)+4.*chi1_s1(3,:,policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(4,:,policy_counter,tipping_counter,breakthrough_counter))./state.delta^2;
chi1.dss(state.number+1,:,policy_counter,tipping_counter,breakthrough_counter)=(2.*chi1_s1(state.number+1,:,policy_counter,tipping_counter,breakthrough_counter)-5.*chi1_s1(state.number,:,policy_counter,tipping_counter,breakthrough_counter)+4.*chi1_s1(state.number-1,:,policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(state.number-2,:,policy_counter,tipping_counter,breakthrough_counter))./state.delta^2;
chi2.dss(2:state.number,:,policy_counter,tipping_counter,breakthrough_counter)=(chi2_s1(3:(state.number+1),:,policy_counter,tipping_counter,breakthrough_counter)-2*chi2_s1(2:state.number,:,policy_counter,tipping_counter,breakthrough_counter)+chi2_s1(1:(state.number-1),:,policy_counter,tipping_counter,breakthrough_counter))./state.delta^2;
chi2.dss(1,:,policy_counter,tipping_counter,breakthrough_counter) =(2.*chi2_s1(1,:,policy_counter,tipping_counter,breakthrough_counter)-5.*chi2_s1(2,:,policy_counter,tipping_counter,breakthrough_counter)+4.*chi2_s1(3,:,policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(4,:,policy_counter,tipping_counter,breakthrough_counter))./state.delta^2;
chi2.dss(state.number+1,:,policy_counter,tipping_counter,breakthrough_counter)=(2.*chi2_s1(state.number+1,:,policy_counter,tipping_counter,breakthrough_counter)-5.*chi2_s1(state.number,:,policy_counter,tipping_counter,breakthrough_counter)+4.*chi2_s1(state.number-1,:,policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(state.number-2,:,policy_counter,tipping_counter,breakthrough_counter))./state.delta^2;
chi1.dtautau(:,2:temperature.number,policy_counter,tipping_counter,breakthrough_counter)=(chi1_s1(:,3:(temperature.number+1),policy_counter,tipping_counter,breakthrough_counter)-2*chi1_s1(:,2:temperature.number,policy_counter,tipping_counter,breakthrough_counter)+chi1_s1(:,1:(temperature.number-1),policy_counter,tipping_counter,breakthrough_counter))./temperature.delta^2;
chi1.dtautau(:,1,policy_counter,tipping_counter,breakthrough_counter) =(2.*chi1_s1(:,1,policy_counter,tipping_counter,breakthrough_counter)-5.*chi1_s1(:,2,policy_counter,tipping_counter,breakthrough_counter)+4.*chi1_s1(:,3,policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(:,4,policy_counter,tipping_counter,breakthrough_counter))./temperature.delta^2;
chi1.dtautau(:,temperature.number+1,policy_counter,tipping_counter,breakthrough_counter)=(2.*chi1_s1(:,temperature.number+1,policy_counter,tipping_counter,breakthrough_counter)-5.*chi1_s1(:,temperature.number,policy_counter,tipping_counter,breakthrough_counter)+4.*chi1_s1(:,temperature.number-1,policy_counter,tipping_counter,breakthrough_counter)-chi1_s1(:,temperature.number-2,policy_counter,tipping_counter,breakthrough_counter))./temperature.delta^2;
chi2.dtautau(:,2:temperature.number,policy_counter,tipping_counter,breakthrough_counter)=(chi2_s1(:,3:(temperature.number+1),policy_counter,tipping_counter,breakthrough_counter)-2*chi2_s1(:,2:temperature.number,policy_counter,tipping_counter,breakthrough_counter)+chi2_s1(:,1:(temperature.number-1),policy_counter,tipping_counter,breakthrough_counter))./temperature.delta^2;
chi2.dtautau(:,1) =(2.*chi2_s1(:,1,policy_counter,tipping_counter,breakthrough_counter)-5.*chi2_s1(:,2,policy_counter,tipping_counter,breakthrough_counter)+4.*chi2_s1(:,3,policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(:,4,policy_counter,tipping_counter,breakthrough_counter))./temperature.delta^2;
chi2.dtautau(:,temperature.number+1,policy_counter,tipping_counter,breakthrough_counter)=(2.*chi2_s1(:,temperature.number+1,policy_counter,tipping_counter,breakthrough_counter)-5.*chi2_s1(:,temperature.number,policy_counter,tipping_counter,breakthrough_counter)+4.*chi2_s1(:,temperature.number-1,policy_counter,tipping_counter,breakthrough_counter)-chi2_s1(:,temperature.number-2,policy_counter,tipping_counter,breakthrough_counter))./temperature.delta^2;

% Drifts
chi1.mu(:,:,policy_counter,tipping_counter,breakthrough_counter)=(chi1.dt(:,:,policy_counter,tipping_counter,breakthrough_counter)+chi1.ds(:,:,policy_counter,tipping_counter,breakthrough_counter).*state.drift.*state.mesh.*(1-state.mesh)+chi1.dtau(:,:,policy_counter,tipping_counter,breakthrough_counter).*temperature.drift+0.5*chi1.dss(:,:,policy_counter,tipping_counter,breakthrough_counter).*state.variation.*state.mesh.^2.*(1-state.mesh).^2+0.5*chi1.dtautau(:,:,policy_counter,tipping_counter,breakthrough_counter).*temperature.variation)./chi1.d(:,:,policy_counter,tipping_counter,breakthrough_counter);
chi2.mu(:,:,policy_counter,tipping_counter,breakthrough_counter)=(chi2.dt(:,:,policy_counter,tipping_counter,breakthrough_counter)+chi2.ds(:,:,policy_counter,tipping_counter,breakthrough_counter).*state.drift.*state.mesh.*(1-state.mesh)+chi2.dtau(:,:,policy_counter,tipping_counter,breakthrough_counter).*temperature.drift+0.5*chi2.dss(:,:,policy_counter,tipping_counter,breakthrough_counter).*state.variation.*state.mesh.^2.*(1-state.mesh).^2+0.5*chi2.dtautau(:,:,policy_counter,tipping_counter,breakthrough_counter).*temperature.variation)./chi2.d(:,:,policy_counter,tipping_counter,breakthrough_counter);

% Volatility Vectors
chi1.sigma1(:,:,policy_counter,tipping_counter,breakthrough_counter)=chi1.ds(:,:,policy_counter,tipping_counter,breakthrough_counter).*state.mesh.*(1-state.mesh).*(production.sigma(2).*production.rho12-production.sigma(1))./chi1.d(:,:,policy_counter,tipping_counter,breakthrough_counter);
chi1.sigma2(:,:,policy_counter,tipping_counter,breakthrough_counter)=chi1.ds(:,:,policy_counter,tipping_counter,breakthrough_counter).*state.mesh.*(1-state.mesh).*production.sigma(2).*sqrt(1-production.rho12^2)./chi1.d(:,:,policy_counter,tipping_counter,breakthrough_counter);
chi1.sigma3(:,:,policy_counter,tipping_counter,breakthrough_counter)=chi1.dtau(:,:,policy_counter,tipping_counter,breakthrough_counter).*temperature.sigma.*temperature.mesh./chi1.d(:,:,policy_counter,tipping_counter,breakthrough_counter);
chi2.sigma1(:,:,policy_counter,tipping_counter,breakthrough_counter)=chi2.ds(:,:,policy_counter,tipping_counter,breakthrough_counter).*state.mesh.*(1-state.mesh).*(production.sigma(2).*production.rho12-production.sigma(1))./chi2.d(:,:,policy_counter,tipping_counter,breakthrough_counter);
chi2.sigma2(:,:,policy_counter,tipping_counter,breakthrough_counter)=chi2.ds(:,:,policy_counter,tipping_counter,breakthrough_counter).*state.mesh.*(1-state.mesh).*production.sigma(2).*sqrt(1-production.rho12^2)./chi2.d(:,:,policy_counter,tipping_counter,breakthrough_counter);
chi2.sigma3(:,:,policy_counter,tipping_counter,breakthrough_counter)=chi2.dtau(:,:,policy_counter,tipping_counter,breakthrough_counter).*temperature.sigma.*temperature.mesh./chi2.d(:,:,policy_counter,tipping_counter,breakthrough_counter);

% Dividends
div1_s1=chi1_s1.^leverage.phi;
div2_s1=chi1_s1.^leverage.phi;