function export_master_status(t)
% EXPORT_MASTER_STATUS  Machine-written consolidated status of a master run
% (editorial-roadmap Step 2). Never a one-line placeholder: records
% timestamp, MATLAB/Dynare versions, every stage run or skipped with the
% reason, figure/table counts, key output-file timestamps, and the
% implementation-status summary.
%
% INPUT t: tracking struct from run_green_deficits_master with fields
%   .t_start .clock0 .projdir .run .skipped .reasons .fast

    tabdir = fullfile(t.projdir, 'output', 'tables');
    figdir = fullfile(t.projdir, 'output', 'figures');
    if ~isfolder(tabdir), mkdir(tabdir); end

    sf  = fullfile(tabdir, 'master_status.txt');
    fid = fopen(sf, 'w');
    if fid < 0
        warning('export_master_status:open', 'Cannot open %s', sf);
        return;
    end

    fprintf(fid, 'GREEN DEFICITS MASTER RUN -- consolidated status\n');
    fprintf(fid, '================================================\n\n');
    fprintf(fid, 'started : %s\n', t.t_start);
    fprintf(fid, 'finished: %s\n', datestr(now, 'yyyy-mm-dd HH:MM:SS'));
    fprintf(fid, 'elapsed : %.1f s\n', etime(clock, t.clock0));
    fprintf(fid, 'MATLAB  : %s\n', version);
    if exist('dynare_version', 'file') == 2
        try
            fprintf(fid, 'Dynare  : %s\n', dynare_version());
        catch
            fprintf(fid, 'Dynare  : on path, version call failed\n');
        end
    else
        fprintf(fid, 'Dynare  : not on the MATLAB path\n');
    end
    fprintf(fid, 'FAST    : %d\n\n', t.fast);

    fprintf(fid, '--- STAGES RUN (%d) ---\n', numel(t.run));
    for k = 1:numel(t.run), fprintf(fid, '  %s\n', t.run{k}); end
    fprintf(fid, '\n--- STAGES SKIPPED (%d) ---\n', numel(t.skipped));
    for k = 1:numel(t.skipped)
        fprintf(fid, '  %-28s reason: %s\n', t.skipped{k}, t.reasons{k});
    end

    % ---- artifact counts + key file timestamps ----
    figs = [dir(fullfile(figdir, '*.pdf')); dir(fullfile(figdir, '*.png'))];
    tabs = dir(fullfile(tabdir, '*.txt'));
    fprintf(fid, '\n--- ARTIFACTS ---\n');
    fprintf(fid, 'figures (pdf+png): %d in output/figures\n', numel(figs));
    fprintf(fid, 'tables  (txt)    : %d in output/tables\n', numel(tabs));
    keyfiles = { ...
        'output/tables/regimes_summary.txt'; ...
        'output/tables/maturity_summary.txt'; ...
        'output/tables/safe_asset_channel_summary.txt'; ...
        'output/tables/welfare_groups_extended_summary.txt'; ...
        'output/tables/transitions_summary.txt'; ...
        'output/tables/rank_transition_validation.txt'; ...
        'output/tables/hank_irfs_summary.txt'; ...
        'output/tables/hank_tier1_validation.txt'; ...
        'output/tables/transition_dtpl_summary.txt'; ...
        'output/calibrated_results.mat'; ...
        'output/channels_results.mat'; ...
        'output/transition_results.mat'; ...
        'data/wb_panel.csv'};
    fprintf(fid, '\nkey output files (timestamp = reproducibility record):\n');
    for k = 1:numel(keyfiles)
        f = fullfile(t.projdir, keyfiles{k});
        if exist(f, 'file') == 2
            d = dir(f);
            fprintf(fid, '  %-52s %s  (%d bytes)\n', keyfiles{k}, d.date, d.bytes);
        else
            fprintf(fid, '  %-52s ABSENT\n', keyfiles{k});
        end
    end

    % ---- implementation-status summary (mirrors MODEL_STATUS.md) ----
    fprintf(fid, '\n--- IMPLEMENTATION STATUS (detail: MODEL_STATUS.md) ---\n');
    L = { ...
    'steady-state HA price-level block (DTPL) .......... IMPLEMENTED'; ...
    'climate v1/v2 + incidence gradient ................ IMPLEMENTED'; ...
    'self-financing decomposition ...................... IMPLEMENTED'; ...
    'safe-asset-channel decomposition (Step 4) ......... IMPLEMENTED (run: see safe_asset_channel_summary.txt)'; ...
    'financing regimes R1-DEFICIT/R2-PROP-LEVY/'; ...
    '  R3-PROP-LEVY-REBATE/R4-MIXED-DEFICIT-LEVY ....... IMPLEMENTED (endowment/proportional-levy tier; NO Pigouvian margin)'; ...
    'welfare by wealth quintile ........................ IMPLEMENTED'; ...
    'extended welfare groups (income/bond/constrained/'; ...
    '  MPC-proxy/exposure) (Step 5) .................... IMPLEMENTED (run: see welfare_groups_extended_summary.txt)'; ...
    'debt maturity / indexation / holders / q_g ........ IMPLEMENTED (arithmetic + bounds tier)'; ...
    'production Stage 1 (tax-base split) ............... IMPLEMENTED (aggregate layer; NOT joined to HA block; labor margin ABSENT)'; ...
    'RANK/NK transitions (U6) .......................... IMPLEMENTED -- RANK/NK TRANSITION DIAGNOSTIC, not DTPL'; ...
    'tier-1 HANK IRFs (U7 tier 1) ...................... IMPLEMENTED -- LINEARIZED, not the nonlinear DTPL transition'; ...
    'nonlinear HANK-DTPL transition (U7 tier 2) ........ IMPLEMENTED (v1; run in the master -- convergence per transition_dtpl_summary.txt)'; ...
    'aggregate stochastic climate risk ................. NOT YET IMPLEMENTED'; ...
    'clean/dirty production, Pigouvian margin (U8) ..... NOT YET IMPLEMENTED'; ...
    'E1 anchor regression .............................. IMPLEMENTED'; ...
    'E4 WB panel regression ............................ DATA DOWNLOADED, estimates pending user run'; ...
    'E2 green-budget denomination panel ................ PLACEHOLDER (schema only; no data fabricated)'; ...
    'E3 event study .................................... PROPOSED'};
    for k = 1:numel(L), fprintf(fid, '%s\n', L{k}); end

    fclose(fid);
    fprintf('  [saved] %s\n', sf);
end
