function Om2 = push_forward_twoasset_x(Om, polB, polK, rb, q, d, tau, pe)
% PUSH_FORWARD_TWOASSET_X  One-period forward push of the (nx x ne)
% distribution over cash-on-hand, under given portfolio policies and the
% prices/taxes that are realized NEXT period.
%
%   x' = y' - tau' + (1 + r^b') b' + (q' + d) k'
%
% with a Young (2010) lottery on the x-grid for each (node, e') pair.
%
% WHY THIS IS A SHARED FUNCTION. The transition residual and the initial
% condition it starts from must be generated by the SAME operator. They were
% not: the steady-state routine leaves x' unclamped while the transition
% push clamps it to the grid, so the stationary distribution supplied as the
% date-1 state was the fixed point of a slightly different map. That
% inconsistency put a floor of about 1.5e-4 under the transition residual,
% which in turn swamped the finite-difference Jacobian near the solution and
% stalled the Newton solve well short of market clearing. One operator, used
% for both, removes the floor by construction.

    xG = pe.xGrid(:); nx = numel(xG); ne = numel(pe.eGrid);
    ynet = pe.eGrid(:)' - tau; Rb = 1 + rb;
    Om2 = zeros(nx, ne);
    for ie = 1:ne
        col = Om(:, ie);
        if ~any(col), continue; end
        base = Rb*polB(:, ie) + (q + d)*polK(:, ie);
        for jep = 1:ne
            xp  = min(max(ynet(jep) + base, xG(1)), xG(end));
            idx = discretize(xp, xG);
            idx(~isfinite(idx)) = nx - 1;
            idx = min(max(idx, 1), nx-1);
            w   = min(max((xp - xG(idx))./(xG(idx+1) - xG(idx)), 0), 1);
            pm  = pe.Pi(ie, jep);
            Om2(:, jep) = Om2(:, jep) ...
                + accumarray(idx,   col.*(1-w)*pm, [nx 1]) ...
                + accumarray(idx+1, col.*w*pm,     [nx 1]);
        end
    end
end
